### ISSUE TITLE
Maven dependencies

### ISSUE THREAD

**Issue by akera-io** [eclipse-sirius/sirius-web#102]
Trying to build a sample diagram editor for our model here, looks like some dependencies are not available in maven repo on github:
- sirius-web-frontend is missing
- sirius-web-spring, sirius-web-services, sirius-web-graphql were not published for 0.4.3, latest version is 0.4.1

Is there a reason some of those components are kept in sirius-web while most of them are in sirius-components?

It's probably to early to start a real web diagram editor right now, we're simply looking into sirius-web and emf.cloud but most probably our GMF runtime implementation will have to live a little longer. 

Thanks,
Marian

**Comment by pcdavid** [comment]
The `sirius-web-spring`, `sirius-web-services`, `sirius-web-graphql` (among others) were previously (until 0.4.1) included in the `sirius-components` repo, which hosts only generic and reusable components. New use cases made it clear that these particular components are not _that_ generic and actually deal with "how to integrate the reusable components into a full-fledged application (with application-specific choices)", and different applications may want to do things differently.

They have now been moved into the `sirius-web` repo, which currently does not publish its resulting JARs.

Currently the best way to consume the latest version is to fork/copy the whole `sirius-web` repo and adapt it. You may only need to adapt `sirius-web-sample-application` to register your own metamodel and modelers, but now you can also extend/customize the other integration components which are there if needed.

**Comment by sbegaudeau** [comment]
I'll close this issue since an answer has been provided. Feel free to reopen it if there is an issue with this answer.
