### ISSUE TITLE
Explicitly list npm v7 in requirements

### ISSUE THREAD

**Issue by Gelio** [eclipse-sirius/sirius-web#111]
Hey,

I've been trying to compile the sample application myself and I have been having trouble with building the frontend:

```sh
14:39 $ npm run build

> @eclipse-sirius/sirius-web@0.4.6 build /home/voreny/projects/studia/magisterka/sirius-web/frontend
> react-scripts build -- --profile

Creating an optimized production build...
Failed to compile.

./node_modules/snabbdom-virtualize/lib/strings.js
Cannot find module: 'snabbdom/h'. Make sure this package is installed.

You can install this package by running: npm install snabbdom/h.
```

It turns out that the problem was using npm v6. For some reason, the installation (`npm ci`) succeeded, but it did not install `snabbdom`.

Node 14 ships with npm v6 by default, so if it's expected to use npm v7, I would suggest putting that as the requirement so others don't encounter a similar confusing problem

Thanks!

**Comment by pcdavid** [comment]
Thanks. We had updated the README [on Sirius Components](https://github.com/eclipse-sirius/sirius-components/commit/f500f97dc63517f54200cb137d66b17c73c98a1e#diff-1194561cbea346acb1bea37d81fdf5c70def982dcbb0c64eca2a96bc51941124), but forgot to update the Sirius Web part.
