### ISSUE TITLE
Split the DiagramServer in listeners/handlers

### ISSUE THREAD

**Issue by hmarchadour** [eclipse-sirius/sirius-web#129]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

The current SiriusWebWebSocketDiagramServer handle too many concepts.
Sprotty provide listener and handler that we can use to isolate the growing complexity of this code.

We can rename SiriusWebWebSocketDiagramServer in DiagramModelSource to use the sprotty vocabulary.

### Cuttings backs

None

### Potential side effects

Front-end diagram

### Describe alternatives you've considered

None

**Comment by pcdavid** [comment]
This concerns the old Sprotty-based diagram frontend. Obsolete.
