### ISSUE TITLE
Provide a diagram description with unsynchronized nodes

### ISSUE THREAD

**Issue by hmarchadour** [eclipse-sirius/sirius-web#136]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

Provide an API to build programmatically a diagram description with unsynchronized nodes.
Provide a sample of a diagram description that use this API and contains unsynchronized nodes/create tools/drop tool.

### Cuttings backs

None

### Potential side effects

None

### Describe alternatives you've considered

The sample diagram could be created on a test meta-model (to provide) to be able to expose all use-cases.

**Comment by sbegaudeau** [comment]
This API has been merged a long time ago.
