### ISSUE TITLE
Resize the node with the minimum width of its inner Label

### ISSUE THREAD

**Issue by lfasani** [eclipse-sirius/sirius-web#1375]
* [X] **I have checked that this feature has not yet been suggested by someone else.**

### Current behavior
Currently, if the node has been manually resized and when the label is changed, the node is never resized.

### Expected behavior
Even if the node has been manually resized, if the label is an inner label 
when the label is changed, the node width will have the minimum size to fully display its label.
...

### Cuttings backs

...

### Potential side effects

...

### Describe alternatives you've considered

* Label with line return
* Label with ellipse
Both cases are too complex to be managed rapidly.
A dedicated enhancement with a spec should be define in the future to better handle this scenario

**Comment by sbegaudeau** [comment]
Closing this issue since we will move in another direction with the support of wrapping for labels
