### ISSUE TITLE
Switch to Spring Boot 3 and Java 17

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#1377]
This change will only be performed after the general availability of Spring Boot 3 (we won't move to a milestone). We may not switch to the release 3.0.0 just after its release and we may wait for a 3.0.x or even a 3.1.x release. This issue is just here to start discussing this migration and the changes required by this new version.

See https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0

**Comment by sbegaudeau** [comment]
Among the changes which may impact us :

- Switch from `javax.xxx` dependencies to `jakarta.xxx` for example `import javax.servlet` to `import jakarta.servlet`
- Potential switch to `PathPatternParser` from the `AntPatternParser` (not strictly required but encouraged)

**Comment by sbegaudeau** [comment]
See https://github.com/spring-projects/spring-boot/releases/tag/v3.0.0

**Comment by sbegaudeau** [comment]
Things to consider:

- Spring Security 5.8 to prepare the migration to Spring Security 6.0.0 [here](https://docs.spring.io/spring-security/reference/5.8/migration/servlet/config.html)
- Migration to Spring security 6.0 [here](https://docs.spring.io/spring-security/reference/migration/index.html)
- Spring Data 2022.0 release notes [here](https://github.com/spring-projects/spring-data-commons/wiki/Spring-Data-2022.0-%28Turing%29-Release-Notes)

We will have to keep in mind that:

- Methods like `authorizeRequests` and `antMatchers` have been deprecated in Spring Security 5.8 and removed in 6.0 and this will have some impact on our security configuration. By switching from Spring Boot 2.7.x to Spring Boot 3.X, we will directly move from Spring Security 5.7.x to Spring Security 6.x and thus encounter the API breaks in question.
- We are extending `PagingAndSortingRepository` in multiple interfaces in `sirius-web-persistence` and this interface will now longer extend `CrudRepository` so any piece of code using things like `IProjectRepository` or `IDocumentRepository` would stop having access to methods such as `findById`, `delete`, `save`. To restore this behavior, our various repositories will have to switch to `extends PagingAndSortingRepository<XXX, YYY>, ListCrudRepository<XXX, YYY>`.

We may also encounter some changes in websocket support or method security, but I haven't evaluated those parts yet.

**Comment by sbegaudeau** [comment]
The migration to Spring Boot 3.0.x will be put on hold for now since it will require a new version of AQL which will have to rely on Antlr 4.10 like the [recent versions of hibernate](https://github.com/hibernate/hibernate-orm/discussions/4975). After multiple tests, hibernate cannot work with anything less than Antler 4.10 and AQL does not work with this version. It's a bit surprising since AQL, which requires Antler 4.7.2 was working fine with Antler 4.8 at least (with a red warning in the console).

The code required for the migration is done, it works until you have to evaluate and AQL expression.

**Comment by pcdavid** [comment]
https://spring.io/blog/2023/01/11/spring-framework-6-0-4-available-now

**Comment by pcdavid** [comment]
If we stay on Spring Boot 2.7 for now, we should upgrade to the latest. As of yesterday this is https://github.com/spring-projects/spring-boot/releases/tag/v2.7.8
