### ISSUE TITLE
The setSelection is called even if the selection did not changed

### ISSUE THREAD

**Issue by lfasani** [eclipse-sirius/sirius-web#1401]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest 2022.9.3

* [x] **I have specified my environment** : 
- All

### Screenshots

...

### Steps to reproduce

scenario 1
* open any model 
* open the dev tools to see the subscription messages
* in the tree explorer, click on any element -> the Form subscription is initialized
* re-click on the same element 
KO -> the Form subscription is stopped and another one is initialized

scenario 2
* same beghavior when clicking twice on a diagram element

### Expected behavior

If the selection does not change, nothing should happen

### Actual behavior

...

**Comment by lfasani** [comment]
we also have the issue when clicking twice in the diagram on a diagram element

**Comment by sbegaudeau** [comment]
Closing this issue
