### ISSUE TITLE
Improve the customization of parametric SVG

### ISSUE THREAD

**Issue by gcoutable** [eclipse-sirius/sirius-web#1435]
We should be able to customize the layout of a specific parametric SVG like adding a wider label padding right.
The actual behavior does not make that possible:
![image](https://user-images.githubusercontent.com/4439675/197499273-54c4f3b2-272b-4f02-a8bf-d4555ad5f060.png)

**Comment by sbegaudeau** [comment]
If I understand things correctly we can currently configure ELK for all SVG mapping but not one kind of mapping specifically ?

I haven’t looked in details to the code of the SVG integration but is the padding around the label something which has to be configured in ELK or could it be specified in the SVG directly with some padding there?

**Comment by adaussy** [comment]
Currently, we have no information regarding the Label in the SVG image. 
So the idea was to have a way to add ELK information by Parametric SVG type.

Basically in this use case I would like to express for a Parametric Image of type "Note" set the width of the figure always X pixel bigger than the label. 
I'm not sure it if it is related but in the case of a Package, I would like to express the fact that the children should not be moved in the top box header. But in that case it depends on the size of the header, so I don't think it related.

**Comment by frouene** [comment]
Thanks to [custom node](https://github.com/eclipse-sirius/sirius-web/pull/2499), you can manage the label rendering as you wish.



![Image](https://github.com/eclipse-sirius/sirius-web/assets/128395825/3fbf4f32-eba6-4e11-a761-27323342518e)
