### ISSUE TITLE
Add support for the direct edit of the start and end labels of an edge

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#1463]

**Comment by pcdavid** [comment]
This caused a regression: I get an NPE in `CompatibilityInitialDirectEditElementLabelProvider` when trying to trigger a direct-edit on an edge which does not have begin/end labels. We do `edge.getBeginLabel().getId().equals(labelId)` but `edge.getBeginLabel()` can be `null`.

I'll propose a PR.
