### ISSUE TITLE
Charts widgets created in the Form Description Editor are incomplete/invalid

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#1477]
When creating a BarChart or PieChart in the Form Description Editor (by DnD), the WidgetDescription instances created are incomplete. In particular they have no `name`, which causes an NPE in `ViewFormDescriptionConverterSwitch.casePieChartDescription(PieChartDescription)` or `ViewFormDescriptionConverterSwitch.caseBarChartDescription(BarChartDescription)` (on `.label(viewPieChartDescription.getName())`).

Once one of these widgets have been added, and until the user configures them properly, the resulting Form Description is invalid. It can not be instanciated, and existing instances of the form can not be re-opened: `ViewConverter.convert()` catches the NPE and returns nothing for this form description.

This is related to https://github.com/eclipse-sirius/sirius-components/pull/1449#issuecomment-1303624548: the way `AddWidgetEventHandler` creates instances of the Widget Description classes can not ensure they are well-formed.

For this particular issue we could try and initialize the `BarCharDescrption` and `PieChartDescription` with non-broken values in `AddWidgetEventHandler` but that is rather _ad-hoc_.
Note than setting a non-null name is not enough: it fixes the conversion but produces a Form which crashes when rendered.

**Comment by sbegaudeau** [comment]
Can this be closed? It seems to have been referenced from a pull request but not linked to it (on purpose?) a month ago. @AxelRICHARD @pcdavid

**Comment by AxelRICHARD** [comment]
Yes it can be closed.
