### ISSUE TITLE
Add the ability to retrieve and set the selection of the workbench from outside

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#1545]
Selection handling is currently managed by the `Workbench` frontend component, which is only part (although the main one) of the project edition view/page (`EditProjectView`).

Actions of the `EditProjectView` which are _not_ part of the workbench (for example in the navbar and its menu) should also be able to read and set the selection.

**Comment by pcdavid** [comment]
#1546 will be implemented/fixed to validate that an action invoked from the project navbar (here the New Document modal) can change the selection.

**Comment by gcoutable** [comment]
Since #1556 was old I preferred to start from scratch.
I reused the ADR and made some small changes.
I will put my PR out of draft once 2023.8.0 will have been released.
