### ISSUE TITLE
Export of UML diagram image cuts at the border

### ISSUE THREAD

**Issue by frankbenoit** [eclipse-sirius/sirius-web#1554]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [na] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest 7.0.4
- other: please specify
* [x] **I have specified my environment** : 
- my computer: Windows

### Screenshots
![image](https://user-images.githubusercontent.com/8962790/210629471-554627a2-f041-4b30-bfd0-3fc94cad6bed.png)

### Steps to reproduce
Export an image to svg or png.

### Expected behavior
The image should not have defects.

### Actual behavior
The frames of the classes are ok, except those that touch the outer border of the exported image.
It seems the image frame is exactly on the lines of the class frame, hence it appears to be thinner compared to the others.

**Comment by pcdavid** [comment]
Hi,
This repository is for Sirius Web.
Your issue concerns Sirius Desktop which, for the moment, is still hosted on the Eclipse Foundation's infrasructure. In particular, issues related to Sirius Desktop should be created on [the Eclipse Bugzilla](https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Sirius).
