### ISSUE TITLE
Expand a container Node after collapse doesn't reveal all children

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-web#1691]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
- All

### Screenshots

![Expand-Collapse](https://user-images.githubusercontent.com/717752/217770680-e346b8e6-e466-4455-9414-bd3e1917bcca.gif)

### Steps to reproduce

A container Node with some sub nodes. Collapse the container and then try to expand it. The children are not all visible, they are on top of each other.

### Expected behavior

After an expand, all children are visible.

### Actual behavior

After an expand, the children are on top of each other, and lead to think there is only one child existing.

**Comment by AxelRICHARD** [comment]
The problem is not specific to expand/collapse and also occurs on the creation of several elements at the same time in a container Node.

**Comment by frouene** [comment]
With react-flow the behavior is as desired.
![collapse_nodes](https://github.com/eclipse-sirius/sirius-web/assets/128395825/35934a2d-90ea-4b4e-862a-cc9368d233ae)
