### ISSUE TITLE
The support for wrapped labels has introduced a performance regression

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#1703]
Using a papaya diagram, the incremental layout can now take several seconds to perform the layout

<img width="2103" alt="Capture d’écran 2023-02-14 à 14 04 58" src="https://user-images.githubusercontent.com/422587/218748251-f7b1ceb2-de46-4ac7-8814-77c99b39c108.png">

**Comment by pcdavid** [comment]
I reopened the original ticket (#1583); the fix is in https://github.com/eclipse-sirius/sirius-components/pull/1704
