### ISSUE TITLE
Incremental layout and ELK do not always agree on the height of containers with compartment

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#1724]
Move a class (2 compartments) on Papaya, the container is extended vertically so that both compartments have the same height.
Apply an arrange all: the compartment which has children is resized to the min height needed to display its children, but the empty compartment gets a bigger height (the default?)

https://user-images.githubusercontent.com/10608/219399109-8d5677a2-9c9f-4982-96aa-19d944dbd2e2.mp4

This is also visible in this scenario:

https://user-images.githubusercontent.com/10608/219399333-d392d7af-0c17-4f7f-90b2-c4df1cce06fe.mp4

**Comment by mcharfadi** [comment]
Closed since with the adoption of ReactFlow it's not relevant anymore.
