### ISSUE TITLE
It is possible to trigger the direct edit on a diagram element which does not have direct edit tools

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#1757]
Steps to reproduce:

- Create a diagram with a node without any direct edit tool
- The direct edit tool does not appear in the palette
- F2 can still trigger the direct edit

**Comment by sbegaudeau** [comment]
Double clicking on the label or starting to type may also trigger the direct edit

**Comment by pcdavid** [comment]
Duplicate of #1712 ?

**Comment by sbegaudeau** [comment]
You're right, I'll close this one
