### ISSUE TITLE
Multi-line label layout with a list child layout strategy does not produce the same layout all the time

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#1765]
Steps to reproduce, in an unsynchronized diagram since it's easier to reproduce this way:

- Create an object a multiline label
- Create a node for this object
- Create child nodes inside

Repeat the same operations in a different order this time (create the node and then change its label to a multiline one, etc)

**Comment by pcdavid** [comment]
Works on 2023.3.0.
