### ISSUE TITLE
Build failed at `npm ci`

### ISSUE THREAD

**Issue by mt-empty** [eclipse-sirius/sirius-web#18]
I'm getting the following error after running `npm ci` from the frontend directory

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.pkg.github.com/eclipse-sirius/zen-observable/-/zen-observable-0.8.15.tgz
npm ERR! 404 
npm ERR! 404  'zen-observable@https://npm.pkg.github.com/eclipse-sirius/zen-observable/-/zen-observable-0.8.15.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/someuser/.npm/_logs/2020-12-07T03_32_57_036Z-debug.log
```

I have created  `$HOME/.npmrc` and `$HOME/.m2/settings.xml` with the appropriate $GITHUB_USERNAME and $GITHUB_ACCESS_TOKEN

**Comment by pcdavid** [comment]
Hi.

Are you using node 14? I know node 15 (the most recent) comes with a new version of npm which handles dependencies in a different way. I have never seen this particular error.
I just tried with a fresh clone of `eclipse-sirius/sirius-web` and can not reproduce. I'm using:

```
% node -v
v14.15.1
% npm -v
6.14.8
```

**Comment by mt-empty** [comment]
Changing to v14.15.1 resolved the the issue
