### ISSUE TITLE
Performance issues with 'Big Guy Flow (17k elements)'

### ISSUE THREAD

**Issue by Camork** [eclipse-sirius/sirius-web#1817]
This demo project show us the capacity of loading huge elements, but it's slow to response.

cpu: i7
memory: 16GB

**Comment by pcdavid** [comment]
We've made several improvements since this was opened (with hopefully more to come).

On current master (2024.7.5), opening a project with 130k elements (the "Sirius Web" Papaya example, we don't have "Big Guy" anymore) takes about 1s to 1.5s.
