### ISSUE TITLE
Add support for tools' preconditions

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-web#182]
Handle https://github.com/eclipse-sirius/sirius-components/issues/779 in sirius-web by:
-Adding new DataFetcher for toolSections
-Supporting new API IIdentifierProvider#findVsmElementId

**Comment by sbegaudeau** [comment]
While it's not an issue, you don't need to create a Sirius Web specific issue for your Sirius Web PR, you can just reuse the issue number and URL of the Sirius Components issue (number 779). It's easier this way.
