### ISSUE TITLE
Remove our dependency to the `uuid` NPM package

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#1848]
We only use it to generate v4 UUIDs on the front, and the standard [`crypto.randomUUID()`](https://w3c.github.io/webcrypto/#Crypto-method-randomUUID) does the same and seems to be [available everywhere that counts](https://caniuse.com/mdn-api_crypto_randomuuid).

**Comment by frouene** [comment]
I assign myself this issue
