### ISSUE TITLE
Add the IDiagramElement(s) id in SinglePositionEvent and DoublePositionEvent

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#1852]
Correctly interpreting these events requires knowing inside which node(s) the user clicked when triggering them.
For example when reacting to a node invocation which creates several new nodes/views, this information would be useful to determine which of the new nodes/views rendered should "consume" the `SinglePositionEvent`.

**Comment by sbegaudeau** [comment]
It may also be an edge id in `SinglePositionEvent` ok technically it may also be an edge id in `DoublePositionEvent` but that's tricky 😛 (I should really try that one day)
