### ISSUE TITLE
Npm install error

### ISSUE THREAD

**Issue by joaocarbonell** [eclipse-sirius/sirius-web#1884]
Hi!

I got this error while run npm install in the frontend:

```
E:\siriusWeb\sirius-components\packages\sirius-web\frontend\sirius-web>npm install
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@eclipse-sirius%2fsirius-components - Not found
npm ERR! 404
npm ERR! 404  '@eclipse-sirius/sirius-components@~2023.3.1' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

I try to change the sirius-components versions in the package.json, but stiil to get error.

**Comment by AxelRICHARD** [comment]
Hello,
Do you have a github personal access token? You need to follow this step: https://github.com/eclipse-sirius/sirius-components#github-access-token to be able to build sirius-web.
Regards,

**Comment by AxelRICHARD** [comment]
You will also need to add your personnal access token in your `.npmrc`

Create or edit `$HOME/.npmrc` and add the following line:
`//npm.pkg.github.com/:_authToken=$GITHUB_ACCESS_TOKEN`
Be sure to replace $GITHUB_ACCESS_TOKEN with the value of your acess token.

**Comment by pcdavid** [comment]
To complete Axel's answer a little, our frontend packages are not published in the default NPM registry (`registry.npmjs.org`) but only on GitHub Packages.

You first need to tell NPM that these packages are to be found on GitHub Packages. This is done  by adding `@eclipse-sirius:registry=https://npm.pkg.github.com/eclipse-sirius` into your `.npmrc` (either global in your `HOME` or local to your project).

Then, even though `eclipse-sirius` is a Open Source & public project, GitHub requires that you use a token when accessing the corresponding GitHub Package, see https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-to-github-packages. So you need to create a personal token as mentioned by Axel, and again tell NPM to use that token to authenticate on `npm.pkg.github.com`.
