### ISSUE TITLE
Provide the ability for specifiers to send back error messages to the frontend

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#1912]
It should be possible to send back an error message after the execution of a Java service.

**Comment by frouene** [comment]
# Scope

## Feedback service

- [x] Shape written, reviewed and merged
- [ ] ADR written, reviewed and merged
- [x] FeedbackMessage interface
- [x] FeedbackMessage implementation with spring scope request
- [x] Add feedback msg on error for tool and widget actions.

## Snackbar Mututalization

- [x] Create Toast component
- [x] Switch all Snackbars ref to new Toast comp.
- [ ] Add test

## Improve feedback possibility

- [ ] Add return messages on success payload
- [ ] Add success message to toast comp.
- [ ] Change Toast representation to use multi snackbar
