### ISSUE TITLE
Expose the concept of Page in the form support of the view DSL

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#1915]

**Comment by frouene** [comment]
## Page concept

- [x] Shape written, reviewed and merged
- [x] ADR written
- [x] View DSL updated
- [x] Add page to the user interface
- [x] Add page mutation to the GraphQL API and implementation
- [x] Cypress tests
- [x] Integration test
- [ ] Add test case for homologation
- [ ] Capture proper screenshots for the CHANGELOG and the documentation

## Page toolbar action

- [ ] View DSL updated
- [ ] Implementation of the UI
- [ ] Cypress tests
- [ ] Add test case for homologation
