### ISSUE TITLE
Simplify the programmatic creation of view models

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#1921]
In a project `sirius-components-view-builder`, depending pretty much only on `sirius-components-view`, we should provide utility classes to help the creation of view based models. You can have a look at the content of `org.eclipse.sirius.web.sample.papaya.view` to see some of the needs of such API.

A detailed ADR will be necessary to gather some feedback first.

**Comment by mcharfadi** [comment]
= Scope

== First task

- [x] Shape written, reviewed and merged
- [ ] ADR written, reviewed and merged

== Second task

- [x] Introducing sirius-components-view-builder and Papaya use the newly created interface
- [ ] First prototype of builder for nodes used in Papaya
- [ ] Second prototype of builder for other concepts used in Papaya
- [ ] First prototype of the naming convention for the cache mechanism

== Third task

- [ ] User guide updated with screenshots
- [ ] Integrated tests updated
