### ISSUE TITLE
Direct edit on View based diagram element leads to infinite loop 

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-web#1929]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- 2023.3.3
* [x] **I have specified my environment** : 
- All

### Screenshots

...

### Steps to reproduce

Try to direct edit a label on a diagram element based on a View diagram description.

### Expected behavior

The direct edit is executed without any errors.

### Actual behavior

An infinite loop occurs on the backend side.

**Comment by pcdavid** [comment]
Note: this only occurs when editing labels of *nodes* (not edges).
