### ISSUE TITLE
Add a new project sirius-components-view-builder

### ISSUE THREAD

**Issue by mcharfadi** [eclipse-sirius/sirius-web#1960]
Add a project sirius-components-view-builder with :

- IdBuilderMap
- IDiagramElementDescriptionProvider
- IEdgeDescriptionProvider
- INodeDescriptionProvider
- INodeToolProvider
- IRepresentationDescriptionProvider

**Comment by sbegaudeau** [comment]
No need to details something that small as an issue, just reuse https://github.com/eclipse-sirius/sirius-components/issues/1921 or rename the issue to detail the benefits of this task. Something like "Extract generic code from the Papaya sample to help create view models"

**Comment by mcharfadi** [comment]
I used the issue 1921 to reference the PR then.
