### ISSUE TITLE
Failed to collect dependencies at fr.obeo.dsl.designer.sample.flow:fr.obeo.dsl.designer.sample.flow:jar:1.0.5-SNAPSHOT

### ISSUE THREAD

**Issue by luxingxiao** [eclipse-sirius/sirius-web#2]
When building the project sirius-web-sample-application, fr.obeo.dsl.designer.sample.flow:fr.obeo.dsl.designer.sample.flow:jar:1.0.5-SNAPSHOT artifact can not be found.

**Comment by luxingxiao** [comment]
When using the project's maven settings.xml, problem is solved.

**Comment by rkvsraman** [comment]
You maven is not configured to pull artefacts from github 

You need to generate a github token ( details here https://stackoverflow.com/questions/58919401/installing-packages-from-github-npm-registry-auth-error-401 )

Modify settings.xml in cloned sirius-web and add the token.

**Comment by alejandrorueda** [comment]
I have configured the user and token in the settings.xml of sirius-web, the token has all the permissions, but I get the following error:
**Failed to read artifact descriptor for fr.obeo.dsl.designer.sample.flow:fr.obeo.dsl.designer.sample.flow:jar:1.0.5-SNAPSHOT: Could not transfer artifact fr.obeo.dsl.designer.sample.flow:fr.obeo.dsl.designer.sample.flow:pom:1.0.5-SNAPSHOT from/to github-sirius-components (https://maven.pkg.github.com/eclipse-sirius/sirius-components): Authentication failed for https://maven.pkg.github.com/eclipse-sirius/sirius-components/fr/obeo/dsl/designer/sample/flow/fr.obeo.dsl.designer.sample.flow/1.0.5-SNAPSHOT/fr.obeo.dsl.designer.sample.flow-1.0.5-SNAPSHOT.pom 401 Unauthorized**

**Comment by pcdavid** [comment]
Thanks for the feedback. The need for a GitHub Access Token and how to configure it for both NPM and Maven is now mentioned in [a new section in the README](https://github.com/eclipse-sirius/sirius-web#github-access-token).

Modifying the `settings.xml` from the repo as mentionned above would work *if you run the build with `-s path/to/settings.xml`*, but it is dangerous to put your personal token in plain text in a file part of a Git repo, as you are a mistake away to push it to a public repo or PR.

It is safer to only put your token in the default `$HOME/.m2/settings.xml` outside of any Git clone, and let Maven use this (no need to use `-s path/to/settings.xml` as `$HOME/.m2/settings.xml` is the default).
