### ISSUE TITLE
The type of SELF is not consistent when used in Details View or in Form Description representation

### ISSUE THREAD

**Issue by adaussy** [eclipse-sirius/sirius-web#2032]
In a detail view context, the type of self is a List of object.

```java
public Optional<FormDescription> aggregate(List<FormDescription> formDescriptions, List<Object> objects, IObjectService objectService, IEditingContext editingContext) {
        VariableManager pageVariableManager = new VariableManager();
        pageVariableManager.put(VariableManager.SELF, objects);
```

Whereas in EditingContextRepresentationDescriptionsEventHandler

```java
 private List<RepresentationDescriptionMetadata> findAllCompatibleRepresentationDescriptions(IEditingContext editingContext, Object object) {
        List<RepresentationDescriptionMetadata> result = new ArrayList<>();
        var kind = this.objectService.getKind(object);
        var clazz = this.resolveKind(editingContext, kind);

        if (clazz.isPresent()) {
            var allRepresentationDescriptions = this.representationDescriptionSearchService.findAll(editingContext);

            for (IRepresentationDescription description : allRepresentationDescriptions.values()) {
                VariableManager variableManager = new VariableManager();
                variableManager.put(VariableManager.SELF, object);
                variableManager.put(IRepresentationDescription.CLASS, clazz.get());
                Predicate<VariableManager> canCreatePredicate = description.getCanCreatePredicate();
```

This cause issues when evaluating the _PreconditionExpression_ since the same service can *not* be reused in both cases.

*Moreover*, it seems the _Domain Type_ of the _FormDescription_ is not used to filter the _PageDescriptions_ available in the _Detail View_. If we want to reuse the _org.eclipse.sirius.components.view.emf.form.ViewFormDescriptionConverter.canCreateForm(FormDescription, VariableManager, AQLInterpreter)_ method it seems that the implementation does not expected a list of element here.

```java
private List<RepresentationDescriptionMetadata> findAllCompatibleRepresentationDescriptions(IEditingContext editingContext, Object object) {
        List<RepresentationDescriptionMetadata> result = new ArrayList<>();
        var kind = this.objectService.getKind(object);
        var clazz = this.resolveKind(editingContext, kind);

        if (clazz.isPresent()) {
            var allRepresentationDescriptions = this.representationDescriptionSearchService.findAll(editingContext);

            for (IRepresentationDescription description : allRepresentationDescriptions.values()) {
                VariableManager variableManager = new VariableManager();
                variableManager.put(VariableManager.SELF, object);
                variableManager.put(IRepresentationDescription.CLASS, clazz.get());
                Predicate<VariableManager> canCreatePredicate = description.getCanCreatePredicate();
                boolean canCreate = canCreatePredicate.test(variableManager);
                if (canCreate) {
                    Object targetObject = object;
                    this.representationDescriptionsProviders.forEach(provider -> {
                        if (provider.canHandle(description)) {
                            var descriptions = provider.handle(editingContext, targetObject, description);
                            result.addAll(descriptions);
                        }
                    });
                }
            }
        }
        return result;
    }
 ```

**Comment by sbegaudeau** [comment]
- Add domainType on PageDescription in the view DSL
- Filter on each instance instead of the whole collection `self` in the FormDescriptionAggregator
- In `IPropertiesDescriptionRegistry`, we should have a method `void add(PageDescription pageDescription);`
- We should provide a variable named `selection` in the FormDescriptionAggregator and the `PropertiesEventProcessorFactory` for the form description of the details view using multiple selection

**Comment by adaussy** [comment]
@sbegaudeau I think the _org.eclipse.sirius.components.collaborative.forms.FormEventProcessor.refreshForm()_ should also be modified. SELF is the first object in `this.formCreationParameters.getObjects()` and selection is the entire collection `this.formCreationParameters.getObjects()` right?

**Comment by sbegaudeau** [comment]
- We can't set the value of selection automatically like that since only some usage of `FormEventProcessor` would use `formCreationParameters.getObjects()` as selection. It has does not match the reality for instances of `FormEventProcessor` created from `FormEventProcessorFactory`.
- The `FormComponent` performs the iteration on the list of objects so I don't think that it's necessary change the value of `self` here
