### ISSUE TITLE
Shapes for NodeStyle 

### ISSUE THREAD

**Issue by sezginaytac** [eclipse-sirius/sirius-web#209]
Hi :)  I want to use some shapes for NodeStyle (e.g. Actor in your youtube demos). But the Spape select box displays "None". Probably, I should provide shape resources (svg, png, etc) in somewhere. How can I provide shapes to the sirius web example app built myself? Many thanks in advance for your consideration...

**Comment by pcdavid** [comment]
Hi.
At the moment there is no UI to add new shapes.
The only way to contribute shapes is to start the backend with the Java system propertyu `org.eclipse.sirius.web.customImages.path` pointing to a directory with the images you want. All images found inside the directory (recursively) will be added as custom images/shapes on startup by the [`CustomImagesLoader`](https://github.com/eclipse-sirius/sirius-web/blob/master/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/CustomImagesLoader.java).

**Comment by sezginaytac** [comment]
It works :) Thanks very much for your quick response.
Best regards,

**Comment by sezginaytac** [comment]
One more note for the interested users:

I realized that the custom images are loaded by [CustomImagesLoader](https://github.com/eclipse-sirius/sirius-web/blob/master/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/CustomImagesLoader.java) and the stored in `customimage `table in the PostgreSql db. 

So,
-  It is sufficient that you can load the images in folder once, i.e., no need to use  [CustomImagesLoader](https://github.com/eclipse-sirius/sirius-web/blob/master/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/CustomImagesLoader.java) by setting the system property in **each** app start.
- After a while, you may want to change the resources and want not-to-use the old images. In that case, I think that you may purge unwanted images from the `customimage` table.
