### ISSUE TITLE
Drag'n'drop from the explorer is not available when the representation is selected

### ISSUE THREAD

**Issue by frouene** [eclipse-sirius/sirius-web#2140]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
 Windows

### Screenshots

https://github.com/eclipse-sirius/sirius-components/assets/128395825/a9cb4ad8-ba6d-4bb6-a6b6-d073af531d89

### Steps to reproduce

* Create a representation with a reference widget.
* Try to drag'n'drop element in the widget when the representation is selected

### Expected behavior

It's possible to use drag'n'drop even when the representation is selected in the tree explorer.

### Actual behavior

Nothing happen

**Comment by pcdavid** [comment]
I see the same broken beahvior on a diagram:

1. Create a Robot Flow and a "Topography unsynchronized" diagram on it.
2. In the explorer, select "Central_Unit" and then drag and drop "CaptureSubsystem" on the diagram: it works, the new node appears.
3. Remove the node from the diagram (delete the view, not the actual semantic element).
4. In the explorer, select "Topography unsynchronized" and then drag and drop "CaptureSubsystem" on the diagram: this time it does not work.

https://github.com/eclipse-sirius/sirius-components/assets/10608/7a754e3c-eef5-47e3-9d23-ab53ea2bff65
