### ISSUE TITLE
Some characters typed in the filter bar raise exception 

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-web#2152]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- 2023.6.4
* [x] **I have specified my environment** : 
- All

### Steps to reproduce

1. Activate the filter bar in the Explorer view
2. Type one of the RegExp special characters ^, /, $, (, *, [....

### Expected behavior

The filter bar accepts all characters

### Actual behavior

The filter bar raise an exception

**Comment by sbegaudeau** [comment]
It would be better to remove the regex entirely than make it even more complex.
