### ISSUE TITLE
"Expand All" does not always reveal the last level

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#2155]
Here I have a representation on the leaf node "standard", but it is not revealed by the first "Expand All":

https://github.com/eclipse-sirius/sirius-components/assets/10608/a4d84b5a-24ad-436e-8618-830e67f81a7d

**Comment by AxelRICHARD** [comment]
"Representations" leaf nodes were not taken into account if they were the only child.
