### ISSUE TITLE
Missing testing infrastructure to ensure reliability of Cypress tests

### ISSUE THREAD

**Issue by jerome-obeo** [eclipse-sirius/sirius-web#2183]
- data-testid = 'upload-document' is not unique (used for menu entry and dialog button)
- data-testid = 'apply-profile' is not unique (used for menu entry and dialog button)
- data-testid = 'apply-stereotype' is not unique (used for menu entry and dialog button)
- page descriptions (tabs): have no testid
- group descriptions have no testid
- FlexContainer descriptions have no testid 
- Text area description has two TextArea elements in the DOM, data-testid could differentiate
- Select dropdown menu has no testid
- Notification feedback (notistack) has no testid
- List description has no testid (only found in elements of the list)
- Dialog popup has no testid
- Elements in stereotype List (in Advanced tab) have testid with volatile id (unusable)

**Comment by frouene** [comment]
* apply-profile and apply-stereotype don't exist in sirius-component.
* The two TextArea elements in the DOM, are generated by MUI Textfield component, we don't have the possibility to add data-testid on these parts.
* We don't create directly the snackbar with notistck, it's complicated to add test-id on it.
* Wich dialog are you talking about ?

**Comment by jerome-obeo** [comment]
It seems that I was looking for a testid in a dialog which is part of our frontend. So I could certainly add it by myself.
