### ISSUE TITLE
Reduce the amount of business code in DiagramRenderer

### ISSUE THREAD

**Issue by gcoutable** [eclipse-sirius/sirius-web#2235]
Prevent the `DiagramRenderer` used to render the diagram with react flow to finish like the `DiagramRepresentation` used to render the diagram with Sprotty, with a lot of business code hard to maintain.

- [ ] https://github.com/eclipse-sirius/sirius-components/issues/2233
- [x] https://github.com/eclipse-sirius/sirius-components/issues/2231

**Comment by sbegaudeau** [comment]
Reopening this since the PR has not been merged
