### ISSUE TITLE
[Question] How to use ReactFlow diagram?

### ISSUE THREAD

**Issue by luxingxiao** [eclipse-sirius/sirius-web#2239]
I found that starting from the 2023.6.6 version, the ReactFlow module has been added to the Diagram components. How should this component be used? Will Sprotty be completely migrated to ReactFlow in the future?

**Comment by pcdavid** [comment]
Yes, the end-goal is indeed to replace the Sprotty-based diagram rendering with one based on React Flow. For the moment, the React Flow version is considered experimental and not ready to be used. We hope to get feature parity with the Sprotty version (with a more reliable layout), and maybe make the switch around October.
