### ISSUE TITLE
Let nodes keep a specific aspect ratio

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#2255]
- It should be possible to define nodes which should stick to a specific aspect ratio (for example, I want an image based node to stick to a `1:1` or `16:9` aspect ratio.
- See `NodeResizer#keepAspectRatio` and the layout algorithm to enforce the aspect ratio on the frontend
- Unit tests should be added to ensure that the layout algorithm keeps the aspect ratio in all conditions

**Comment by pcdavid** [comment]
Only the shape has been merged for the moment, not the actual implementation.
