### ISSUE TITLE
Add the ability to contribute new node types

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#2256]
It should be possible to contribute new node types using a `DiagramNodeTypeContribution` with the same philosophy as `TreeItemContextMenuContribution`.

Nodes contributed this way should be able to perform the same as default node types:

- Be movable and resizable
- Be able to display a label
- Support the palette, the direct edit
- Have the ability to create edges from / to such nodes etc

**Comment by pcdavid** [comment]
Reopening: the shape was merged, but not the actual code yet.
