### ISSUE TITLE
Ensure that layout constraints are respected

### ISSUE THREAD

**Issue by gcoutable** [eclipse-sirius/sirius-web#2290]
## Goals

- [x] https://github.com/eclipse-sirius/sirius-web/issues/2480
- [x] https://github.com/eclipse-sirius/sirius-web/issues/1982
- [ ] https://github.com/eclipse-sirius/sirius-web/issues/2481
- [x] https://github.com/eclipse-sirius/sirius-web/issues/2482
- [x] https://github.com/eclipse-sirius/sirius-web/issues/2483
- [x] https://github.com/eclipse-sirius/sirius-web/issues/2484
- Support for multiple labels

### Feature parity between rectangular and image nodes

Combine both `RectangularNode` and `ImageNode` into a `FreeFormNode` in the frontend. In a similar fashion, we should thus have only a `FreeFormNodeLayoutHandler`. We may change the GraphQL API / Programmatic API later but this is not an issue for now. It will allow image nodes to have children and to support the drop of semantic elements. The image could be connected to the node by using CSS background property.

See:
- `background-image: url("../img/blog.png") no-repeat center center;`
- `background-size: contain;`
- `background-repeat: no-repeat;`

Test with an image node with child nodes to see the result

#### Optional labels

There will be two kinds of labels, 0..1 label inside (and 0..12 labels outside, will be done later).
The inside label should be optional. An optional label is not an empty label, there are no direct edit support (double click, typing, F2, direct edit tool in the palette)

In the View DSL, the inside label should be a dedicated concepts `InsideLabelDescription` contained by a `NodeDescription` with the `labelExpression` it should not change anything on the label style properties contained by NodeStyle.

- Papaya should be updated in order to display nodes without an inside label
- ReactFlow should also be updated to support nodes without an inside label
- List nodes support should be updated to handle the lack of a label

#### Position

The inside label can be positioned on:
- TOP_LEFT
- TOP_CENTER
- TOP_RIGHT
- LEFT_CENTER
- CENTER
- RIGHT_CENTER
- BOTTOM_LEFT
- BOTTOM_CENTER
- BOTTOM_RIGHT

The label needs to contain its location. We need to add the following concepts:

```
public enum InsideLabelLocation {
  TOP_LEFT,
  TOP_CENTER,
  TOP_RIGHT,
  LEFT_CENTER,
  CENTER,
  RIGHT_CENTER,
  BOTTOM_LEFT,
  BOTTOM_CENTER,
  BOTTOM_RIGHT,
}
```

```
// Rename the existing LabelDescription to InsideLabelDescription
public class InsideLabelDescription {
  private Function<VariableManager, InsideLabelLocation> location;
}
```

```
// Rename the existing Label to InsideLabel
public class InsideLabel {
  private InsideLabelLocation location;
}
```

```
public class Node {
  private InsideLabel label;
}
```

At this point in time, we will not be able to have outside labels anymore. In the odesign compatibility layer the inside label will be configured to `TOP_CENTER` while it will be configurable in the View DSL.

This should be tested with list nodes

### Header

A header can be used to prevent child nodes from overlapping the label area. The header can be located at the top for TOP_XXX labels, the bottom for BOTTOM_XXX labels and on the left for LEFT_CENTER and on the right for RIGHT_CENTER labels.

A CENTER label cannot have the property header -> This should not be possible in the creation of the InsideLabel#build() and we should thus throw an IllegalArgumentException here to prevent this use case from ever reaching the frontend. Add the class in a whitelist for the GeneralPurposeTests class. In the view DSL, always remove the header option, when converting, even if the option is true when the label's location is CENTER.

In a node with a list layout strategy, the label must be a header. Throw an exception if that's not the case. In the view DSL, always set the header option to true if the parent node has a list layout strategy even if the option is set to false.

`org.eclipse.sirius.components.diagrams.RectangularNodeStyle#withHeader` should move to `InsideLabelDescription`.

### Outside label

- Add the ability to have multiple outside labels:
  - TOP_{BEGIN | MIDDLE | END}
  - RIGHT_{BEGIN | MIDDLE | END}
  - BOTTOM_{BEGIN | MIDDLE | END}
  - LEFT_{BEGIN | MIDDLE | END}

**Comment by mbats** [comment]
Check that this change allows the support of the rectangular with header style.

**Comment by sbegaudeau** [comment]
Closing this issue since individual issues have been created to track the progress on various topics
