### ISSUE TITLE
Support Palette on Edges on react-flow diagrams

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-web#2313]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

...

### Cuttings backs

...

### Potential side effects

...

### Describe alternatives you've considered

...

**Comment by sbegaudeau** [comment]
Reopening this issue since a new PR has been attached to it. It should also be moved in the project to be visible in the relevant milestone
