### ISSUE TITLE
Add Node data type and Edge data type to every hook useReactFlowInstance

### ISSUE THREAD

**Issue by gcoutable** [eclipse-sirius/sirius-web#2380]
Add a guard on `useReactFlowInstance(` in the `check-ts.js` script

**Comment by Zutzsa** [comment]
@gcoutable , can I work on this issue?

Should this condition be added in `check-ts.js` at line _58_ together with the first `else if` condition or after the last `else if` at line _65_?

**Comment by gcoutable** [comment]
> @gcoutable , can I work on this issue?
> 
> Should this condition be added in `check-ts.js` at line _58_ together with the first `else if` condition or after the last `else if` at line _65_?

Sorry for the later answer, I just saw it.
I just push a PR to fix it.

Best regards
