### ISSUE TITLE
Graphical Dnd is not possible on container node description from hight depth level

### ISSUE THREAD

**Issue by jessymallet** [eclipse-sirius/sirius-web#2509]
Graphical DnD is only possible on container display on the diagram or on container in an other container. On deeper container (for example a container in an other container contained in an other one), graphical DnD is not authorized. The container is not fade but it is not highlighted 

* [X] **I have checked that this bug has not yet been reported by someone else**
* [X] **I have specified the version** : 2023.10.4
* [X] **I have specified my environment** :  Windows 11

### Screenshots

![failGraphicalDnD](https://github.com/eclipse-sirius/sirius-web/assets/24290600/b94b1d49-e39f-4497-b1f4-a1a9cb3d428f)

### Steps to reproduce

Create 3 nested containers and try to DnD a node description on the deepest container.  It should work.

### Expected behavior

It should be possible to DnD element graphically on each container, whatever their depth level on the diagram. 

### Actual behavior

It is only possible to DnD element graphically on node description on the first or second depth level.

**Comment by pcdavid** [comment]
There's something more than just the depth at play here, I have no issue dropping elements in even deeper hierarchies on another diagram:

https://github.com/eclipse-sirius/sirius-web/assets/10608/2683584c-e5b3-487e-a72f-a806a69372de
