### ISSUE TITLE
Close the diagram palette on Escape

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#2552]
Contextual palette should close by clicking on the X at the end of the toolbar => K.O. no X at the end.

**Comment by pcdavid** [comment]
For palette closing on move/zoom, see https://github.com/eclipse-sirius/sirius-web/issues/2550

**Comment by mbats** [comment]
We do not want an"X" anymore but it should be possible to close the palette with "echap". It works for pretty well on a node but not when the palette is open on the diagram directly.

**Comment by pcdavid** [comment]
Actually what happens when we hit "Esc" while a node is selected (and its palette visible) is *not* that _we_ close the palette.

It's that React Flow de-selects the node, and *that* triggers the disappearance of the palette. In every node component we have somehting like:

```jsx
{selected ? <DiagramElementPalette diagramElementId={id} labelId={data.label ? data.label.id : null} /> : null}
```

But when it's the diagram that is selected, hiting "Esc" does not "unselect" anything.

So we got the expected behavior for elements "for free" but also by chance, and we need to do something specific for the case of the diagram.
