### ISSUE TITLE
Add some padding the PageAction

### ISSUE THREAD

**Issue by adaussy** [eclipse-sirius/sirius-web#2600]
The page action buttons overlaps the Page bottom bar. 

![image](https://github.com/eclipse-sirius/sirius-web/assets/4439675/f4b3170f-96ad-41cd-b573-0a1f636e0516)

The icon should be smaller to avoid this effect.

**Comment by sbegaudeau** [comment]
The padding should probably be in the page showing both the navigation bar and the groups.
