### ISSUE TITLE
The project doesn't work locally

### ISSUE THREAD

**Issue by DayronDLR** [eclipse-sirius/sirius-web#261]
- First I tried to find the image of the project in Docker, but it doesn't exist.
- Next, I cloned the repository and follow the steps to run it locally, but I get:

![image](https://user-images.githubusercontent.com/37316384/225129914-a9e3c498-1036-45de-a34a-ef86ef4d1c65.png)

I'm doing some research to implement a DSL with Langium and I think Sirius complements what I'm looking for. However, I would need to have a Stable version of the project. Can you help me?.

**Comment by joaocarbonell** [comment]
Did you solve your issue?
