### ISSUE TITLE
The palette remains open when the selection is changed outside of the diagram

### ISSUE THREAD

**Issue by jessymallet** [eclipse-sirius/sirius-web#2612]
Tool palette should be displayed when an element is selected. 
When we open a new project, if user select element in explorer view, the matching node is selected on the diagram but no palette tool is displayed. If user select the node on the diagram, the palette tool is displayed. Then if user select an other element from explorer view, the palette tool is still displayed. 
The display of tool palette is not coherent. 

* [X] **I have checked that this bug has not yet been reported by someone else**
* [X] **I have checked that this bug appears on Chrome**
* [X] **I have specified the version** : 2023.10.6
* [X] **I have specified my environment** : Window 11

### Screenshots

![toolsPalette](https://github.com/eclipse-sirius/sirius-web/assets/24290600/a0cb4375-b493-4e73-bb24-504c5fa1127d)

### Steps to reproduce

1- Create a project and a representation with entity domain
2- Create entity1 and entity2 on the diagram
3- Close and open the diagram
4- Select entity1 from the explorer view : entity1 node is selected on diagram but no palette tool is displayed
5- Click on entity1 node from diagram 
6- Click on entity2 from explorer view : entity2 node is selected and palette tool appears

### Expected behavior

Palette tool should appear when entity1 is selected after opening the project and selected it from explorer view. 

### Actual behavior

Palette tool does not appear when entity1 is selected after opening the project and selected it from explorer view.

**Comment by sbegaudeau** [comment]
> Expected behavior
> 
> Palette tool should appear when entity1 is selected after opening the project and selected it from explorer view.

I strongly disagree on the expected behavior, here the user as not performed any interaction with the diagram, the palette should be closed if the selection is changed from the workbench, not opened on the second element. An interaction in another representation should not start triggering things like that.

**Comment by jessymallet** [comment]
> > Expected behavior
> > Palette tool should appear when entity1 is selected after opening the project and selected it from explorer view.
> 
> I strongly disagree on the expected behavior, here the user as not performed any interaction with the diagram, the palette should be closed if the selection is changed from the workbench, not opened on the second element. An interaction in another representation should not start triggering things like that.

Ok with the behavior that you describe. In this case, palette should not appear when I click on Entry2 from the Explorer (after clicking on entity1 node on diagram) because I click from Explorer so I do not interact with diagram
