### ISSUE TITLE
Diagram selection is not synchronized with Explorer selection

### ISSUE THREAD

**Issue by jessymallet** [eclipse-sirius/sirius-web#2613]
When a node is selected, the palette tool appears systematically in ReactFlow. User can close the palette with "echap" (see https://github.com/eclipse-sirius/sirius-web/issues/2552)  but the node is then deselected. This behavior is weird because the semantic element is still selected in Explorer view and because Properties view still display properties about this element. 

* [X] **I have checked that this bug has not yet been reported by someone else**
* [X] **I have checked that this bug appears on Chrome**
* [X] **I have specified the version** : 2023.10.6
* [X] **I have specified my environment** : Window 11

### Screenshots

![synchSelectionDiagram](https://github.com/eclipse-sirius/sirius-web/assets/24290600/2b91f473-1594-4b99-895e-0686e7664d47)

### Steps to reproduce

1- Open project with entity domain
2- Select an entity node on the diagram
3- Press "Echap" : the node is deselected

### Expected behavior

The node should be still selected in order to be coherent with selection in explorer view and in Properties view.

### Actual behavior
The node is deselected.

**Comment by sbegaudeau** [comment]
> The node should be still selected in order to be coherent with selection in explorer view and in Properties view.

We could also remove the node from the selection of the workbench... I don't have an opinion on either solution, whatever is the easiest to implement.

**Comment by gcoutable** [comment]
This issue is fixed on sirius web2024.3.0
It seems https://github.com/eclipse-sirius/sirius-web/issues/3044 has fixed it.
