### ISSUE TITLE
With React Flow the connection line is lost during relation type choice

### ISSUE THREAD

**Issue by frouene** [eclipse-sirius/sirius-web#2616]
If there are two or more connectorTools on an edge creation, a popup is display to select the wanted connection.
But at this point, we lost the connection line betwenn the two nodes, which can be disturbing for the user.

In sprotty with the magic connector we don't have this behavior.

### Sprotty behavior

![edge_connector_sprotty](https://github.com/eclipse-sirius/sirius-web/assets/128395825/05df5701-581e-412f-8bb9-1939f6ba44e8)

### React flow behavior

![edge_connector_react_flow](https://github.com/eclipse-sirius/sirius-web/assets/128395825/3c5970a2-871f-4ccd-a21c-ab59bc2404e1)

**Comment by pcdavid** [comment]
React Flow resets the `connection` to `null` unconditionally on mouse up: https://github.com/xyflow/xyflow/blob/reactflow%4011.8.1/packages/core/src/components/Handle/handler.ts#L179C21-L180C1
