### ISSUE TITLE
Cannot retrieve Then the latest pre-built JAR:

### ISSUE THREAD

**Issue by filippor** [eclipse-sirius/sirius-web#262]
The last successful job is expired

**Comment by pcdavid** [comment]
The Sirius Web application itself has moved to the eclipse-sirius/sirius-components repo.
You can find the corresponding artefact by looking for `org.eclipse.sirius.sirius-web-sample-application` in [the packages for that repo](https://github.com/eclipse-sirius/sirius-components/packages/).
For example the latest version at this time is 2023.3.2 available at https://github.com/eclipse-sirius/sirius-components/packages/1660490?version=2023.3.2.
You can find the link to the pre-build uber-JAR in the "Assets" section of that page.
