### ISSUE TITLE
Tools from the palette are not triggered if the mouse is moving (even a little)

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#2678]
It's relatively tricky to trigger, but actually happens quite often in practice, and can be confusing.

Steps to reproduce:
1. Open a (React Flow) diagram.
2. Select a node, its palette appears.
3. Move the mouse on one of the palette tools.
4. Without moving the mouse press the left button and _keep it pressed_.
5. Move the mouse (as little as possible, e.g. 1px).
6. Release the mouse button.

The tool is not invoked/triggered. The "scroll/pan the diagram and close any palette" behavior is triggered on the move.

In practice this happens very often when trying to trigger a tool; even a very small mouse move while clicking can make the tool not trigger.

**Comment by mcharfadi** [comment]
This is fixed with node tools https://github.com/eclipse-sirius/sirius-web/pull/2716
This still occurs with tools triggered from a click on the diagram
