### ISSUE TITLE
Nodes can be temporarily faded when clicking/selected another one

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#2681]
With the support for node DnD, when we start moving a node _A_, we fade all other nodes which are not compatible drop targets.

In the first version of DnD, we considered a DnD to be "in progress" only when React Flow had called `onNodeDrag` on our node. See [here](https://github.com/eclipse-sirius/sirius-web/commit/591ddb493cf4a5920a62370c72fbc0f0e69ac1bd#diff-304b6768613ae0428dba2ab4709d1f857ff8816e6a71020094c202cbedcc3d15L198) where we set `draggedNodeId` to `null` in `onNodeDragStart` and only set it to `node.id` in `onNodeDrag`.

After the refactoring done in https://github.com/eclipse-sirius/sirius-web/pull/2620 we now consider a DnD to be "in progress" as soon as React Flow calls `onDragStart`. However this happens even on a plain click to select a node without moving. `onDragStop` is called when the mouse is released.

The consequence is that when clicking on a node, we temporarily fade all nodes which are note compatible drop targets, which causes "flickering" on the diagram.

[Capture vidéo du 2023-11-29 11-10-27.webm](https://github.com/eclipse-sirius/sirius-web/assets/10608/e00405b8-adca-4325-a259-07bd6e6b0c7c)

There is a moment where the "Entity 2" and "bob is typing" nodes are incorrectly faded:

![Capture d’écran du 2023-11-29 11-12-49](https://github.com/eclipse-sirius/sirius-web/assets/10608/0730ac44-dabc-46e6-a5bc-6f9b7c4e4503)

**Comment by mcharfadi** [comment]
It should be possible to use the [node-drag-threshold](https://reactflow.dev/api-reference/react-flow#node-drag-threshold) by upgrading ReactFlow to v11.9.0

**Comment by pcdavid** [comment]
This has been fixed a while ago with bc4342bc7c372df64507b37a559130177faa1fd5.
