### ISSUE TITLE
Child's labels may exceed their container

### ISSUE THREAD

**Issue by frouene** [eclipse-sirius/sirius-web#2721]
### Actual behavior

![image](https://github.com/eclipse-sirius/sirius-web/assets/128395825/236baa48-0ef0-4760-9dfa-286239fb84f2)

**Comment by gcoutable** [comment]
It happens because we do not support outside labels.
The label of an image is considered inside the node to compute its size but is put outside the node.
Outside labels should be implemented in the next iteration.
However, I think I can produce a small fix for image nodes.

**Comment by gcoutable** [comment]
I was not able to produce the small fix since it was not working alone.
It has become a part of something greater.
This issue should be fixed when #2480 will be merged.
