### ISSUE TITLE
Organize module in starters to ease the definition of what is part of application

### ISSUE THREAD

**Issue by lfasani** [eclipse-sirius/sirius-web#2818]
* [X] **I have checked that this bug has not yet been reported by someone else**

### Actual behavior

Currently `sirius-web-sample-application` owns a lot of spring `@Configuration`. It implies dependencies to every representation and various meta-models.(charts, diagram, gantt, deck etc)

### Expected behavior

We should split those configuration and put them in starter module so that an application would have just to choose the starter

Example  of Gantt & Deck:

`ViewGanttDescriptionBuilder` is an example of Gantt view which depends on Gantt and Task meta-model
Gantt and Deck should be used independantly from the Task meta-model and independantly from each other
Using Task for Gantt or Deck should not imply respectively the usage of Deck or Gantt

For such reasons we could imagine having 
* a module containing the Bean for Task
* a module, depending on gantt(`sirius-components-view-gantt` `sirius-components-view-gantt-edit` , `sirius-components-XXX-gantt`, containing for example the Bean for view Gantt (EPackage, AdapterFactory) and ViewGanttConverter (that convert view modele to POJO description)
* a module, depending of the two previous, containing the Bean for the Gantt stereotype that uses `ViewGanttDescriptionBuilder`

**Comment by sbegaudeau** [comment]
I am currently assigned to the reusability and extensibility of the Sirius Web application during the next iteration and as such I have written multiple shapes and ADRs. While we will improve the reusability of Sirius Web, I don't think that we will move on with the approach that you are describing here.
