### ISSUE TITLE
Collapse container node does not reduce the size of the node with ReactFlow

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-web#2846]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- 2023.12.3
* [x] **I have specified my environment** : 
- All

### Screenshots

Expanded node :
<img width="204" alt="Capture d’écran 2023-12-20 à 10 36 09" src="https://github.com/eclipse-sirius/sirius-web/assets/717752/4a7d81bb-4761-4517-b49e-43f42ccbae7d">

Collapsed node:
<img width="209" alt="Capture d’écran 2023-12-20 à 10 36 25" src="https://github.com/eclipse-sirius/sirius-web/assets/717752/d4d467a6-6547-494f-bf11-763a64e014cf">

### Steps to reproduce

Just have a container node with collapsible = true.

### Expected behavior

The collapsed state reduce the size of the container node to its default (or minimum?) size.

### Actual behavior

The collapsed state does not modify the size of the container node.

**Comment by jessymallet** [comment]
An other alternative could be to reduce the size of the compartment after collapse and display a decorator (+/-) to warn the user if the compartment is collapse or not. If all compartment are collapsed, the the container looks like a simple node and it can cause confusion to a new user.

![image](https://github.com/eclipse-sirius/sirius-web/assets/24290600/b24648d2-73f2-4d73-b4b8-58cf4ec60cb9)

**Comment by frouene** [comment]
The new behavior seems to be the desired one.
The size of the collapsed node can be configured using the default value in the _nodeDescription_
![collapse_liste](https://github.com/eclipse-sirius/sirius-web/assets/128395825/fc06c9f8-51a3-427e-a276-de35006fafa8)
