### ISSUE TITLE
Let end users move contained elements

### ISSUE THREAD

**Issue by mbats** [eclipse-sirius/sirius-web#288]
Today, when an element is moved in its container, it is blocked at its borders.
The purpose is to allow the move of an element to another container and manage the semantic consequences.

It should thus be possible to move a child element from one container to another. This should work with free from layouted nodes and list layouted nodes. It should also allow moving border nodes from one node to another.

**Comment by pcdavid** [comment]
Reopening as the main code is merged, but some work is still needed, notably to add tests.

**Comment by pcdavid** [comment]
The tool's execution context is missing the `editingContext` and `diagramContext` variables.
