### ISSUE TITLE
The arrange all breaks compartments nodes

### ISSUE THREAD

**Issue by mcharfadi** [eclipse-sirius/sirius-web#2923]
![4106](https://github.com/eclipse-sirius/sirius-web/assets/121878084/1cd14f3f-03a4-45b0-9b1f-c69e0d66ac59)
To reproduce : change Attributes to FreeForm and execute Arrange All
![image](https://github.com/eclipse-sirius/sirius-web/assets/121878084/239cce0b-d0e6-4f61-ba84-e4e8e2a61b6f)

**Comment by frouene** [comment]
ArrangeAll seems ok with the last version in this configuration.
![arrange_all_freeform](https://github.com/eclipse-sirius/sirius-web/assets/128395825/04d59a5d-80b4-40e4-888b-3a08f64f2e9e)
