### ISSUE TITLE
Unfinished edge creation can leave the diagram in an incorrect state

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#2939]
Steps to reproduce:
1. Create a "Flow" project from the template.
2. Select the "DataSource1", and try to create an edge from it to the "CompositeProcessor1".
3. This does not create an edge, as expected as there are zero compatible edge creation tools.
4. However it leaves the diagram in the state of "edge creation in progress": the mouse cursor when hovering on nodes is a cross (instead of a hand), and while it is possible to *select* elements, they can node be moved.

[Capture vidéo du 2024-01-17 14-56-50.webm](https://github.com/eclipse-sirius/sirius-web/assets/10608/803975ba-0993-4afe-aed4-8a1d5eabf3f8)

Refreshing the page fixes the issue.

**Comment by mcharfadi** [comment]
The PR https://github.com/eclipse-sirius/sirius-web/pull/2906 also fixes this issue

**Comment by pcdavid** [comment]
This was wrongly associted with #2933 and closed when that one was merged.
