### ISSUE TITLE
FormDescriptionEditor does not support read-only mode

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#2999]
Ok, I was trying something a bit fishy here but it works, it just shows a tiny error in the process. If that's the source of the issue, we could probably deactivate the drop area of the portal while we are not editing the representations? @pcdavid what do you think?

https://www.youtube.com/watch?v=jH35IwkkRbo

Anytime I try to drag something inside the form description editor, the portal starts to react which prevents it from having a great user experience. On the screenshot below, I'm trying to drop a checkbox in the form description editor and the portal wants to capture the drop which creates an error too:

<img width="1991" alt="Capture d’écran 2024-01-24 à 14 21 30" src="https://github.com/eclipse-sirius/sirius-web/assets/422587/0b1702df-c99b-49bd-9d90-b66b45b2fc38">

I'm starting to believe that we are "this close" from being able to drag and drop things between representations without issues 😛

**Comment by pcdavid** [comment]
This looks more like a lack of support for read-only mode in Form Description Editor.
In the video, the portal is in "edit" mode, so it is expected that it reacts to dnd operations (though maybe it could *only* react to dnd from representations dropped from the explorer).

**Comment by pcdavid** [comment]
Reworded, as the core issue is actually that Form Description Editors do not support the "read-only" mode. Clearly the Portal's UI could be improved to avoid the confusion, see #2949 for ideas.
