### ISSUE TITLE
How to upload a project?

### ISSUE THREAD

**Issue by YPF1016696863** [eclipse-sirius/sirius-web#30]
After creating a new project, downloading works fine and get 3 JSON file of the model but I wonder how to upload the project by using the same model file containing the 3 JSON? the upload doesn't work at all when I drag one single JSON and then click the upload button.
![截屏2021-01-19 下午7 59 52](https://user-images.githubusercontent.com/13996643/105080393-0a083580-5a91-11eb-817d-e59a70c570c6.png)

**Comment by pcdavid** [comment]
Sorry, I missed your question.

When you download a *project*, you should get a zip archive with all the current contents of the project (models and diagrams).
Uploading expects such an archive as input, and will create a new project with the same state as what was stored in the archive.

You can also download & upload individual models, but it's a different mechanism. "Upload project" expects a full project archive, not an individual file.

See the dopcumentation at https://ocpmodeler.com/doc/2020.10.0/help_center.html#_download_upload fro more details on these.
