### ISSUE TITLE
Open tags option for a sub task crashes the backend 

### ISSUE THREAD

**Issue by frouene** [eclipse-sirius/sirius-web#3018]
### Steps to reproduce

With a task template project:

* select a sub task (like for example _review_ under _development_ in _Project Dev_)
* open the tags option with the reference widget in the details view

### Expected behavior

* the tags are listed as option

### Actual behavior

* the options list stays in loading mode and the backend is crashed (the other requests fail with timeout)

**Comment by frouene** [comment]
The options for the other references (like assigned people) are not consistent to the actual model
![task_references](https://github.com/eclipse-sirius/sirius-web/assets/128395825/6e066708-4802-4a2e-88aa-4fa6e21f94ff)

**Comment by lfasani** [comment]
There are many issues in the xxxProvider used by reference widget for dependencies, persons assignees, team assignees and tags.
But the main issue was an infinite loop in some cases.
That explains the *Loading* status and the backend crash. That also explain why the *referenceValueOptions* mutation was not called next times.
Perhaps there is something to do to make the server more robust for this case.
The first mutation that was in infinite loop should not block the server completly
