### ISSUE TITLE
It is not possible to add the same representation several times in a portal

### ISSUE THREAD

**Issue by frouene** [eclipse-sirius/sirius-web#3204]
It should be possible to have several times the same classic representation or another portal in a portal

![portal](https://github.com/eclipse-sirius/sirius-web/assets/128395825/8e4974bc-4494-4306-a26c-3b9a9bcae7da)

**Comment by lfasani** [comment]
I consider that not having the same representation twice in a portal is the good behavior.
Moreover, currently, it is possible to have a portal P1 in a portal P2 and a given representation can be in P1 and P2

So for me, this ticket can be closed.

**Comment by pcdavid** [comment]
Closing as per @lfasani's remark. We can always re-open later if needed.
