### ISSUE TITLE
Standard tools from diagram palette do not use the same color

### ISSUE THREAD

**Issue by adaussy** [eclipse-sirius/sirius-web#3285]
* [X] **I have checked that this bug has not yet been reported by someone else**
* [X] **I have checked that this bug appears on Chrome**
* [X] **I have specified the version** : Latest
* [X] **I have specified my environment** :  Windows? 

### Screenshots
![image](https://github.com/eclipse-sirius/sirius-web/assets/4439675/091d5401-e5ce-44f0-bcc3-17e369aff6f6)

The direct edit and trash icon does not use the same color as the other tools (Hide, Fade, Pin, Resize)

### Steps to reproduce
Open any palette tool

### Expected behavior

The standard tool should use the "primary" color of the CSS template.

### Analysis:

The tools that use and incorrect color are provided by the backend. The fronted uses a ```<img>``` tag to display the icon for those tools.

```html
<div class="makeStyles-toolSection-207">
  <div class="makeStyles-tool-210" data-testid="Edit - Tool">
    <div style="position: relative; width: 16px; height: 16px">
      <img
        height="16"
        width="16"
        alt="Edit"
        src="http://localhost:8080/api/images/diagram-images/edit.svg"
        class=""
        style="z-index: 0; position: absolute; top: 0px; left: 0px"
      />
    </div>
  </div>
</div>

````

Whereas the working tool are inlined SVG

```html
<button
  class="MuiButtonBase-root MuiIconButton-root makeStyles-toolIcon-258 MuiIconButton-sizeSmall"
  tabindex="0"
  type="button"
  aria-label="Hide element"
  data-testid="Hide-element"
>
  <span class="MuiIconButton-label">
    <svg
      class="MuiSvgIcon-root MuiSvgIcon-fontSizeSmall"
      focusable="false"
      viewBox="0 0 24 24"
      aria-hidden="true"
    >
      <path
        d="M12 7c2.76 0 5 2.24 5 5 0 .65-.13 1.26-.36 1.83l2.92 2.92c1.51-1.26 2.7-2.89 3.43-4.75-1.73-4.39-6-7.5-11-7.5-1.4 0-2.74.25-3.98.7l2.16 2.16C10.74 7.13 11.35 7 12 7zM2 4.27l2.28 2.28.46.46C3.08 8.3 1.78 10.02 1 12c1.73 4.39 6 7.5 11 7.5 1.55 0 3.03-.3 4.38-.84l.42.42L19.73 22 21 20.73 3.27 3 2 4.27zM7.53 9.8l1.55 1.55c-.05.21-.08.43-.08.65 0 1.66 1.34 3 3 3 .22 0 .44-.03.65-.08l1.55 1.55c-.67.33-1.41.53-2.2.53-2.76 0-5-2.24-5-5 0-.79.2-1.53.53-2.2zm4.31-.78l3.15 3.15.02-.16c0-1.66-1.34-3-3-3l-.17.01z"
      ></path>
    </svg>
  </span>
  <span class="MuiTouchRipple-root"></span>
</button>

````

It appears that it is not possible to use a color defined in the application in an SVG that is not inlined.
If we try to set the color in the SVG using _currentColor_ it seems that is has not effect.

```html
<svg
  width="24"
  height="24"
  viewBox="0 0 24 24"
  xmlns="http://www.w3.org/2000/svg"
>
  <path
    d="M13.2215 5.11335L18.8867 10.7799L5.66519 24H0V18.3335L13.2215 5.11201V5.11335ZM15.1099 3.22495L17.9425 0.391017C18.1929 0.140649 18.5325 0 18.8867 0C19.2408 0 19.5804 0.140649 19.8309 0.391017L23.609 4.16915C23.8593 4.41959 24 4.75922 24 5.11335C24 5.46747 23.8593 5.8071 23.609 6.05755L20.775 8.89014L15.1099 3.22495Z"
    fill="currentColor"
    color="currentColor"
  />
</svg>

```
In a simple use case, it seems also impossible to set the style to be used to render an SVG in the ``img`` tag.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <style>
    .fill-red {
      fill: red;
      color: red;
    }
    .fill-blue {
      fill: blue;
      color: blue;
    }
  </style>
  <body>
    <div class="fill-red">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
      >
        <path
          d="M13.2215 5.11335L18.8867 10.7799L5.66519 24H0V18.3335L13.2215 5.11201V5.11335ZM15.1099 3.22495L17.9425 0.391017C18.1929 0.140649 18.5325 0 18.8867 0C19.2408 0 19.5804 0.140649 19.8309 0.391017L23.609 4.16915C23.8593 4.41959 24 4.75922 24 5.11335C24 5.46747 23.8593 5.8071 23.609 6.05755L20.775 8.89014L15.1099 3.22495Z"
          fill="currentColor"
        />
      </svg>
    </div>
    <img
      src="./edit.svg"
      width="50px"
      height="50px"
      class="fill-red"
      color="aqua"
      fill="red"
      style="color: aqua; fill: currentColor"
    />
  </body>
</html>

```
![Rendering result](https://github.com/eclipse-sirius/sirius-web/assets/4439675/22cdc562-df26-4c95-a014-70743575b3d0)

I think the following article says it is a constraint of SVG use in ``img`` tag: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web

A workaround for this use case to work would be to inline the SVG inside the ``IconOverlay`` component if the iconURL is an SVG.

For this we could either create a custom React component that fetch the content of the SVG and inlines it or use a existing library:

https://www.npmjs.com/package/react-svg
...

**Comment by sbegaudeau** [comment]
> I think the following article says it is a constraint of SVG use in `img` tag

Indeed, SVG retrieved from a link are indeed sandboxed from the CSS of the rest of the page. There nothing we can do about that limitation but we still have couple of options to fix the issue.

### Use the proper color in the backend

We could simply change the color used in the SVG in the backend but it would not work for those who will customize that part of the theme of the frontend.

### Move those SVGs to the frontend

One option would be to keep all those static SVGs on the frontend in `sirius-components-diagrams` for those in questions. It would solve that issue but the issue would still appear if someone tried to add custom icons for their diagram tools and if they wanted to use the standard palette.

### Control the theme on the backend

This is not the first feature where we would need to have access to the theme on the backend of the application. Since most of the theme is serializable, it could easily be downloaded by the frontend when the application is starting up. By having the theme on the backend, we could thus give the runtime / specifiers access to the theme to compute stuff such as icons with proper color but also the default color palette in a studio etc.

**Comment by adaussy** [comment]
I guess you did not like the solution that inline the SVG directly in the frontend 😊

So among the three solutions you proposed which one should I implement?

**Comment by adaussy** [comment]
So while waiting for a more advanced solution, I will change the color of the icons to match the current theme of Sirius Web.
