### ISSUE TITLE
Group palette shouldn't  be displayed if only list children are selected

### ISSUE THREAD

**Issue by frouene** [eclipse-sirius/sirius-web#3290]
![image](https://github.com/eclipse-sirius/sirius-web/assets/128395825/2d1d7f63-09ae-4a7f-9cff-7e195aba622b)

The children in a list must be filtered from the selection to determine whether the group palette is displayed or not.

**Comment by gcoutable** [comment]
I don't understand the issue.
In which cases selecting something related to list select many elements?

**Comment by frouene** [comment]
In the screenshot, the _attributes_ and _ports_ container are distinct nodes.
If I select them then it's considered as a mutli selection and opens the group palette but we don't want to apply tool on it (at least distribute element tools)
