### ISSUE TITLE
Align the properties of transient and persisted representations

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#3304]
We should remove `ISemanticRepresentation` and move `targetObjectId` to `IRepresentation`. We should be careful since `ISemanticRepresentation` is used at some places as the way to find out if a representation is transient or not, the issue #3303 should be considered first to stop relying on this.

**Comment by pcdavid** [comment]
The following `IRepresentation` implementations are not `ISemanticRepresentation` and thus do not have a `targetObjectId` at the moment:

* `Validation`
* `Tree` (used for the _Explorer_ view)
* `IChart` (`BarChart` & `PieChart`)

Charts are currently only used in the context of forms via `ChartWidgetComponent`, which computes a `targetObjectId`, so the `IChart` representation itslef could be passed the `targetObjectId` and become a full `ISemanticRepresentation` easily.

For Validation and Tree, there is no semantic element that can serve a the target object.
The most obvious (and maybe the only) value would by the `editingContextId`.

In the same way that we needed to make `IObjectService` aware of representations (in #3066) it should probably be made "editing context aware", i.e. `IIdentityService.getId()` and `IObjectSearchService.getObject()` should work when passed an `IEditingContext` or its id.
