### ISSUE TITLE
Mixing scroll and zoom in Gantt representations make them unusable

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#3366]
By mixing zoom and scroll when you are over the main area of the Gantt representations, the slightest change in the scroll of the Gantt representation can trigger some massive change in the zoom. See how little I scroll in the second part of the following video

https://github.com/eclipse-sirius/sirius-web/assets/422587/40cb621d-69e3-447b-b1d9-b872c3902b7b

**Comment by lfasani** [comment]
It is actually what have been agreed but I dislike as you do the current behavior.
The idea was to fit the behavior in diagram by zooming in/out with the mouse wheel.
But here, in gantt, we are more in a constraint table than in an open field like diagram so I consider that the best behavior is to associate the mouse wheel to the scrollbar.
I will change to have the zoom with `Ctrl+wheel`
