### ISSUE TITLE
Allow contributions in extra tool sections

### ISSUE THREAD

**Issue by gdaniel** [eclipse-sirius/sirius-web#3384]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior
Specifiers can define tools and add them to tool sections automatically created in the palette (delete/hide/fade).
This complements #3382 and would allow to define diagram-specific hide/reveal tools (e.g. "Show compartment XXX") and have them displayed alongside the other hide/reveal tools:

![contribute hide tools](https://github.com/eclipse-sirius/sirius-web/assets/6516281/932343bb-edf7-43d2-b06c-36c3ae3c2002)

Elements in red are default tools detailed in #3382
Elements in green are specific tools contributed by the specifier

### Potential side effects
This opens tool sections of the palette that weren't accessible to specifiers.

### Describe alternatives you've considered
I am not sure what's the best approach to do this, but I have considered the following:
- A name-based approach to merge user-defined tool sections with default ones (e.g. a user can create a "hide" tool section and its tools will be contributed to the default "hide" one)
- A "Palette Post Processor" service that can add/remove elements from the palette once it has been computed (this could help fix #2461 and #3176)

Please let me know if you have a suggestion on the best way to achieve this.

**Comment by sbegaudeau** [comment]
I think that we should continue moving forward with the current strategy where the palette defined in the view model reflect the final content. We have added in this palette the delete and direct edit tools.

<img width="513" alt="Capture d’écran 2024-04-15 à 00 17 07" src="https://github.com/eclipse-sirius/sirius-web/assets/422587/9af25bde-6f6e-4406-b31f-6ecea11af96d">

We should probably just continue by adding there a Show / Fade / Hide tool section with a default tool for show and hide. The currently hardcoded tools "show" and "hide" would just become default tools created in the view DSL (just like the delete and direct edit ones currently). I think the bast solution would be to stop having ANY tool hardcoded in the frontend and have them all computed from the diagram description.

You could start moving on this issue by removing the fact that the tools for show / hide / fade are hardcoded in the palette and make them computed from the diagram description (don't forget to consider removing their dedicated data fetchers too s they make no sense) and we could move forward with this by removing the hardcoded tools and data fetchers for expand, collapse, pin, unpin too later. This way specifiers would be able to remove default tools, replace them, add a condition on them, change their behavior or organize them in tool section as they desire.
