### ISSUE TITLE
Sirius component should not add a "/custom/" prefix on the ImageNodeStyleDescription#shape field

### ISSUE THREAD

**Issue by florianbarbin** [eclipse-sirius/sirius-web#3386]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [ ] **I have checked that this bug appears on Chrome**
* [ ] **I have specified the version** :
- latest
- other: please specify
* [ ] **I have specified my environment** : 
- All
- my computer: Windows? Linux? Cloud?
- Cloud

### Screenshots

...

### Steps to reproduce

In Sirius-web, the shape field of the `ImageNodeStyleDescription` references a custom image uploaded on the server and stored in the  database. The `ImageController` uses the `/custom/` prefix on this image path to know if the image should be retrieved from the database.

But in the context of a spring server based on sirius-component but not Sirius-web, we might use the shape field to store a path to a static resource for instance. Since the `/custom/`prefix is added by sirius-component, we have to deal with it in the ImageController even if the custom image mechanism is not used.

The prefix is added by the ImageNodeStyleProvider :

```java
else if (nodeType.equals(Optional.of(NodeType.NODE_IMAGE))) {
            iNodeStyle = Optional.of(ImageNodeStyle.newImageNodeStyle()
                    .scalingFactor(1)
                    .imageURL("/custom/" + ((ImageNodeStyleDescription) nodeStyle).getShape())
                    .borderColor(Optional.ofNullable(nodeStyle.getBorderColor())
                            .filter(FixedColor.class::isInstance)
                            .map(FixedColor.class::cast)
                            .map(FixedColor::getValue)
                            .orElse(DEFAULT_COLOR))
                    .borderSize(nodeStyle.getBorderSize())
                    .borderStyle(LineStyle.valueOf(nodeStyle.getBorderLineStyle().getLiteral()))
                    .borderRadius(nodeStyle.getBorderRadius())
                    .positionDependentRotation(((ImageNodeStyleDescription) nodeStyle).isPositionDependentRotation())
                    .build());
        }
```

...

### Expected behavior

The `/custom/`  prefix should not be added by sirius-component but probably directly in the ImageNodeStyleDescription at creation time (in the studio or programmatically when using the view builder). 

...

### Actual behavior

...

**Comment by sbegaudeau** [comment]
Closing since the prefix is not there anymore
