### ISSUE TITLE
Do not try to parse representation UUID before checking if it has one.

### ISSUE THREAD

**Issue by ebausson-obeo** [eclipse-sirius/sirius-web#3399]
May be resolved once #3304 & #3305 are solved, but I wanted to signal it anyway:
When opening a project, the server try to parse the representationId as a UUID. In the case of a transcient ID, a warning is logged despite a legitimate value (in my case: `explorer://`). I believe attempting to resolve the representation though `findTransientRepresentationById` first rather than as a fallback would neatly sidestep the issue.

* [X] **I have checked that this bug has not yet been reported by someone else**
* [X] **I have checked that this bug appears on Chrome**
- server side
* [X] **I have specified the version** :
- latest (2024.3.2)
- other: please specify
* [X] **I have specified my environment** : 
- All
- My computer is on Linux / Firefox, but it shouldn't matter in this case.

### Screenshots
![Screenshot from 2024-04-17 16-36-19](https://github.com/eclipse-sirius/sirius-web/assets/136804792/d2cb9b3d-13ec-463b-8289-3fb790f9ad9e)

...

### Steps to reproduce
- create a project
- open project
- warning is in you log despite no actual issue.

...

### Expected behavior
No warning in log when opening a project successfully.
...

### Actual behavior
Warning in log when opening a project successfully.
...

**Comment by sbegaudeau** [comment]
The fix has been merged on master
