### ISSUE TITLE
Performance issue during node drag

### ISSUE THREAD

**Issue by mcharfadi** [eclipse-sirius/sirius-web#3407]
There is a performance issue during node drag due to the `DropNodeContextProvider `making every nodes rerender.
![image](https://github.com/eclipse-sirius/sirius-web/assets/121878084/967ada1b-78cc-42e0-ac3e-5d8410fce64b)
Each time `DropNodeContextProvider `rerender it takes more tan 20ms, below `NodeRenderer `are all the nodes that are rerendered.

**Comment by sbegaudeau** [comment]
@mcharfadi please don't forget the `type:` and `package:` labels too, thx
