### ISSUE TITLE
Register transient representation descriptions in the editing contexts

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#3538]
In the new architecture, [`RepresentationMetadataDescriptionDataFetcher`](https://github.com/eclipse-sirius/sirius-web/blob/master/packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/controllers/RepresentationMetadataDescriptionDataFetcher.java) does not include the special treatment [the old version had](https://github.com/eclipse-sirius/sirius-web/blob/master/packages/sirius-web/backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/representation/RepresentationMetadataDescriptionDataFetcher.java) for find the details view and explorer view's descriptions.

This is normal, but it means a query like `query getReferenceValueOptions()` does not find the details view representation description and (incorrectly) returns null.

The proper solution is for these representation descriptions to be registered inside the editing context when loaded (via an `IEditingContextProcessor#preProcess`) so that they can be found like any other. This also means that `PropertiesEventProcessorFactory`, `RelatedElementsEventProcessorFactory` and `RepresentationsEventProcessorFactory` could get the proper representation description directly from the editing context instead of requesting a new copy of the representation description from their special-purpose providers (e.g. `this.propertiesDefaultDescriptionProvider.getFormDescription()`).

**Comment by gcoutable** [comment]
> The proper solution is for these representation descriptions to be registered inside the editing context when loaded (via an IEditingContextProcessor#preProcess) so that they can be found like any other.

Does that mean `IEditingContextRepresentationDescriptionProvider` is redundant?

**Comment by pcdavid** [comment]
FWIW, partial workaround which fixes the _Reference_ widget until we get a proper/complete fix:

```java
@Service
public class DetailsViewInitializer implements IEditingContextProcessor {

    private final DetailsViewDescriptionProvider detailsViewDescriptionProvider;

    public EditingContextInitializer(DetailsViewDescriptionProvider detailsViewDescriptionProvider) {
        this.detailsViewDescriptionProvider = Objects.requireNonNull(detailsViewDescriptionProvider);
    }

    @Override
    public void preProcess(IEditingContext editingContext) {
        if (editingContext instanceof EditingContext siriusWebEditingContext) {
            siriusWebEditingContext.getRepresentationDescriptions().put(PropertiesEventProcessorFactory.DETAILS_VIEW_ID, this.detailsViewDescriptionProvider.getFormDescription());
        }
    }
}
```

**Comment by pcdavid** [comment]
> This also means that PropertiesEventProcessorFactory, RelatedElementsEventProcessorFactory and RepresentationsEventProcessorFactory could get the proper representation description directly from the editing context

Actually this does not seem possible, at least not without API changes. This would require the representation event processor factories to use `org.eclipse.sirius.web.application.editingcontext.EditingContext.getRepresentationDescriptions()` which is only available in `sirius-web-application`.

I guess we could have:

```java
default Map<String, IRepresentationDescription> getRepresentationDescriptions() {
  return Map.of();
}
```
added directly into `IEditingContext`.
