### ISSUE TITLE
Visible borders appear on all node labels starting from 2024.5.2

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#3669]
#3561 added new style options for labels, but the default (rounded, solid, black border) applies to existing view definitions and change their rendering. I had a simple diagram definition which worked fine before, and moving to 2024.5.2 I now see:

![Capture d’écran du 2024-06-27 11-05-37](https://github.com/eclipse-sirius/sirius-web/assets/10608/651b544b-490c-438f-b32d-d9f79cde5bf0)

I can set to border size to 0 in the newly added properties:

![image](https://github.com/eclipse-sirius/sirius-web/assets/10608/48089aae-8a67-4ce9-aafe-ab15eeceb47b)

But its a strange default to apply to everyone. Either the default should change of, if we really want all newly created node description to have these borders (I don't see a good reason), there should be a migration to avoid impacting existing diagrams which did not ask for this.

**Comment by AxelRICHARD** [comment]
It occurs on Inside, Outside LabelStyle and EdgeStyle
