### ISSUE TITLE
Deleting a representation from the "Representations" view does not work on the new architecture

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#3672]
## Steps to reproduce

1. Open a project with at least one representation.
2. In the Explorer, select the semantic target element of a representation.
3. In the right panel, open the _Representations_ view. It should display the representation in question (with others if there are more).
4. Click on the "Delete" (trashcan) icon in the _Representations_ view to delete the representation.

The representation is not deleted, and we get error messages:

On the front:

> An unexpected error has occurred, please refresh the page

On the backend:

```
o.e.s.c.g.controllers.GraphQLController : {
  "errors" : [ {
    "message" : "The field at path '/deleteListItem' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.  The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'DeleteListItemPayload' within parent type 'Mutation'",
    "path" : [ "deleteListItem" ],
    "extensions" : {
      "classification" : "NullValueInNonNullableField"
    }
  } ],
  "data" : null
}
```

**Comment by gcoutable** [comment]
I also have the same issue trying to remove an element from the list widget.

**Comment by sbegaudeau** [comment]
The issue here is quite simple, this form related data fetcher is only available in the code of the old architecture, I'll move it to `sirius-components-forms-graphql`
