### ISSUE TITLE
In Sirius vscode extention, the content is not displayed

### ISSUE THREAD

**Issue by lfasani** [eclipse-sirius/sirius-web#3726]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- 2024.7.0

### Steps to reproduce

* Install the Sirius VSCode extention. 
  * Download the `vscode` artifact from any PR build based on master (link of a kind https://github.com/eclipse-sirius/sirius-web/actions/runs/xxx) 
  * From VSCode, go to Extensions and use `Install from VSIX ` to install Sirius extension.
* Click on Sirius extenstions in the VSCode left part
* Configure to connect to an existing Sirius Web URL
* Assuming, there is a project containg a semantic resource and diagrams, select the project in `Projects` part

### Expected behavior

`Explorer` part should display the semantic resource

### Actual behavior

An error is displayed:
`Error while retrieving model contents: undefined`

**Comment by gcoutable** [comment]
Where did you get the vscode extension?

**Comment by lfasani** [comment]
> Where did you get the vscode extension?

I updated the scenario

**Comment by lfasani** [comment]
The issue was that VSCode needed to be updated.
Once updated, it works fine?

**Comment by lfasani** [comment]
I need to reopen this ticket because after restarting VSCode I got the same issue than before updating VSCode

**Comment by gcoutable** [comment]
Can you try with the latest vscode extension version (2024.5.5)?

**Comment by lfasani** [comment]
Eventually, the issue came from the fact that the server URL ended with /.
Setting `https://dns` works fine
