### ISSUE TITLE
In Sirius vscode extention, the reference widget can not be displayed

### ISSUE THREAD

**Issue by lfasani** [eclipse-sirius/sirius-web#3727]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- 2024.7.0

### Steps to reproduce

* Install the Sirius VSCode extention
  * Download the `vscode` artifact from any PR build based on master (link of a kind https://github.com/eclipse-sirius/sirius-web/actions/runs/xxx) 
  * From VSCode, go to Extensions and use `Install from VSIX ` to install Sirius extension.
* Ctrl+Shift+P `>Developper : OpenWebview Developper tools` and open Console tab
* Click on Sirius extenstions in the VSCode left part
* Configure to connect to an existing Sirius Web URL
* From frontend, create a `Studio` project
* Open the studio, expand to the Root of the domain model
* Click on the root
-> The details are displayed

### Expected behavior

`Super Types` reference widget should be displayed

### Actual behavior

`Super Types` reference widget is not displayed
Message displayed in Developper Console
`sirius-components-forms.es.js:14835 Unsupported widget type ReferenceWidget`

**Comment by sbegaudeau** [comment]
Fixed in #3943
