### ISSUE TITLE
Expand actions on tree have no effect on the new architecture

### ISSUE THREAD

**Issue by frouene** [eclipse-sirius/sirius-web#3776]
Tested in the widget ref explorer

**Comment by sbegaudeau** [comment]
I'm reopening this issue since the fix contributed does not match what I'm expecting. Please remove all references to the widget reference from the code of the explorer, they are not related one to the other. There's no need to create some coupling between both concepts.

**Comment by frouene** [comment]
> I'm reopening this issue since the fix contributed does not match what I'm expecting. Please remove all references to the widget reference from the code of the explorer, they are not related one to the other. There's no need to create some coupling between both concepts.

Ok, so the correct solution is to duplicate code to impl a `IExpandAllTreePathProvider` in the widget-reference module ?
