### ISSUE TITLE
MigrationParticipant implementation broke conventional ExtendedMetadata mechanism

### ISSUE THREAD

**Issue by adaussy** [eclipse-sirius/sirius-web#3806]
I will use a UML meta model use case to describe this use case.

In the UML metamodel, we can find the following annotation:

![image](https://github.com/user-attachments/assets/f1ef0d0a-2280-4e1e-8303-6a7fa42a315e)

My understanding is that the feature `ownedGroup` needs to be serialized as `group`. (Note there is also a `group` EReference but this one is Derived/Transient/Volatile).

```xml
<packagedElement xmi:type="uml:Activity" xmi:id="_B6tXUEj9Ee-Rp58iMjoc3A" name="Activity1" node="_Ddv3YEj9Ee-Rp58iMjoc3A">
    <node xmi:type="uml:InitialNode" xmi:id="_Ddv3YEj9Ee-Rp58iMjoc3A" name="InitialNode1"/>
</packagedElement>
```

But when this feature is read, it should fill the `ownedGroup` feature.

![image](https://github.com/user-attachments/assets/ae060a4f-f8fc-4d3a-9717-b6961017b2ee)

Previously in _Papyrus Web_, we removed the BasicExtendedMetadata object from the _ResourceSet_ by customizing the _EditingContextSearchService_ and the _EditingContextFactory_. In the new architecture, we replaced this behavior by doing the same in a custom _IEditingContextProcessor_.

However, this is not enough because it is now forced by the following services to plug the MigrationParticipant (since it inherits from BasicExtendedMetadata) behavior:

*  _org.eclipse.sirius.web.application.document.services.JSONExternalResourceLoaderService.getResource(InputStream, URI, ResourceSet)_
* _org.eclipse.sirius.web.application.editingcontext.services.ResourceToDocumentService.toDocument(Resource)_
* _org.eclipse.sirius.web.application.editingcontext.services.ResourceLoader.toResource(ResourceSet, String, String, String)_
* _org.eclipse.sirius.web.application.document.services.DocumentSanitizedJsonContentProvider.getContent(ResourceSet, String, InputStream)_

Resulting in the model in the database looking like:

```json
 {
    "id": "23b6df82-53ac-45ba-865b-2b6b5d61b420",
    "eClass": "uml:Activity",
    "data": {
        "name": "Activity1",
        "group": [
            {
                "id": "2886665f-5abb-4655-8b42-0398d904be94",
                "eClass": "uml:ActivityPartition",
                "data": {
                    "name": "ActivityPartition1",
                    "node": ["//Activity1/ActivityFinalNode2"]
                }
            }
        ],
        "node": [
            {
                "id": "644db420-110a-4ceb-99e0-6730d347d6f6",
                "eClass": "uml:ActivityFinalNode",
                "data": { "name": "ActivityFinalNode1" }
            },
            {
                "id": "18e257f0-f7f5-40ea-aed5-fcfc46c942a7",
                "eClass": "uml:ActivityFinalNode",
                "data": {
                    "name": "ActivityFinalNode2",
                    "inPartition": ["//Activity1/ActivityPartition1"]
                }
            }
        ],
        "partition": ["//Activity1/ActivityPartition1"]
    }
}
```

Whereas before it looked like this:

```json
 {
    "id": "641e61db-8806-4f26-80f0-110edc66146c",
    "eClass": "uml:Activity",
    "data": {
        "name": "Activity1",
        "ownedGroup": [
            {
                "id": "7ac88b8d-ced8-4dc2-8d53-0d5177473840",
                "eClass": "uml:ActivityPartition",
                "data": {
                    "name": "ActivityPartition1",
                    "node": ["//Activity1/ActivityFinalNode2"]
                }
            }
        ],
        "ownedNode": [
            {
                "id": "171cf2f7-a4c4-4450-860a-75bee44f76ad",
                "eClass": "uml:ActivityFinalNode",
                "data": { "name": "ActivityFinalNode1" }
            },
            {
                "id": "a0ddeaf5-01ec-4420-b78d-d1d72c462ff3",
                "eClass": "uml:ActivityFinalNode",
                "data": {
                    "name": "ActivityFinalNode2",
                    "inPartition": ["//Activity1/ActivityPartition1"]
                }
            }
        ],
        "partition": ["//Activity1/ActivityPartition1"]
    }
}
```

This causes the following exception when the model is loaded from the database:

```
java.lang.UnsupportedOperationException: JsonObject
    at com.google.gson.JsonElement.getAsString(JsonElement.java:187) ~[gson-2.10.1.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeMultipleNonContainmentEReference(GsonEObjectDeserializer.java:677) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeEReference(GsonEObjectDeserializer.java:497) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeData(GsonEObjectDeserializer.java:472) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeEClassifier(GsonEObjectDeserializer.java:446) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.loadObject(GsonEObjectDeserializer.java:407) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeMultipleContainmentEReference(GsonEObjectDeserializer.java:869) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeEReference(GsonEObjectDeserializer.java:491) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeData(GsonEObjectDeserializer.java:472) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeEClassifier(GsonEObjectDeserializer.java:446) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.loadObject(GsonEObjectDeserializer.java:407) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
```

EMFJson expects to load a flat ID list as it has encountered a non-containment EReference (`group`) but gets some structured data since it is, in fact, the content of the `ownedGroup` feature.

This problem arises because the _forced_ implementation in the _MigrationService_ does not delegate the computation that retrieves the feature from a name to its superclass implementation:

```java
@Override
public EStructuralFeature getElement(EClass eClass, String namespace, String eStructuralFeatureName) {
    EStructuralFeature structuralFeature = eClass.getEStructuralFeature(eStructuralFeatureName);
    for (IMigrationParticipant migrationParticipant : this.migrationParticipantsCandidates) {
        EStructuralFeature newStructuralFeature = migrationParticipant.getEStructuralFeature(eClass, eStructuralFeatureName);
        if (newStructuralFeature != null) {
            structuralFeature = newStructuralFeature;
        }
    }
    return structuralFeature;
}
```

Moreover, to make it work, we would need to be able to provide our own implementation of _BasicExtendedMetaData_ to override the following method _org.eclipse.emf.ecore.util.BasicExtendedMetaData.isFeatureNamespaceMatchingLax()_ so it can return true.

Maybe a solution would be for the two given services not to directly override the _JsonResource.OPTION_EXTENDED_META_DATA_ option but:

* First, check the ResourceSet if this option is set.
* If it is not, create a _BasicExtendedMetaData_.
* Then compose either the retrieved _ExtendedMetaData_ or the newly created one into the _MigrationService_.

Then modify the MigrationService so it delegates most of its behavior to the given _ExtendedMetaData_.

**Comment by pcdavid** [comment]
So after discussing with the persons involved with the migration service design and implementation, it was a voluntary decision not to base our version of `ExtendedMetaData` on EMF's `BasicExtendedMetaData` (nor delegate to it) as it is too tightly coupled with XML-based concepts which do not map well with our JSON resources.

That being said, the migration service's main use case for the time being (for semantic data) is for *us* (the Sirius Web project) to support transparent backward compatibility for instances of the _View_ and _Domain_ models. It would make sense to make the whole mechanism "opt in", explicitly ask for it on our side for these two kinds of semantic resources, and leave the EMF defaults as before for resources/documents where migration support is not explicitly asked for.
