### ISSUE TITLE
Related elements view can crash with MUI 5

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-web#3849]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- 2024.7.9
* [x] **I have specified my environment** : 
- All

### Stack

```
Error: MUI X: The Tree View component requires all items to have a unique `id` property.
Alternatively, you can use the `getItemId` prop to specify a custom id for each item.
Two items were provided with the same id in the `items` prop: "cf164a01-97ad-4ab1-9ef3-8874dfadbbbe"
    at index-DmZyy1EZ.js:2578:930
    at bS (index-DmZyy1EZ.js:52:54278)
    at eK (index-DmZyy1EZ.js:52:54733)
    at Object.useState (index-DmZyy1EZ.js:52:60651)
    at pl.useState (index-DmZyy1EZ.js:12:6151)
    at n$r (index-DmZyy1EZ.js:2574:7579)
    at index-DmZyy1EZ.js:2580:1637
    at YUe (index-DmZyy1EZ.js:52:53496)
    at yBt (index-DmZyy1EZ.js:52:61687)
    at cnn (index-DmZyy1EZ.js:56:10829)
jBe @ index-DmZyy1EZ.js:54
```

### Steps to reproduce

1/ Use the `Sirius Web` template project
2/ Activate the "Related elements" view
3/ Select the following object:
![Capture d’écran 2024-08-08 à 15 39 26](https://github.com/user-attachments/assets/ffe9f0f5-d810-4723-b28a-2715a4420e95)

The crash occurs

### Expected behavior

No crash

### Actual behavior

Crash

**Comment by pcdavid** [comment]
It looks like this occurs when the selected element references the object multiple times through different references. In this case we include the same referenced element multiple times, and the corresponding tree items have the same ids.
