### ISSUE TITLE
New instances of ReactFlowProvider created on most diagram interactions and never disposed

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#3878]
https://github.com/user-attachments/assets/a52d58cf-bb26-4d0b-bdf9-44dab7b46e5d

This seems related to the `ReactDOM.render(element, hiddenContainer, renderCallback);` when doing [client-side layout](https://github.com/eclipse-sirius/sirius-web/blob/master/packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layout.tsx#L201).

**Comment by mcharfadi** [comment]
Adding `ReactDOM.unmountComponentAtNode(container);` in `cleanLayoutArea` seems to fix the issue.
