### ISSUE TITLE
Add support for a REST API

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#3979]
See the [Systems Modeling Application Programming Interface (API) and Services](https://www.omg.org/spec/SystemsModelingAPI/1.0/Beta1/PDF)  section "8.1 REST/HTTP PSM". We will consider at least both the `ProjectService` and `ElementNavigationService`.

Additional resources:

- https://www.omg.org/spec/SystemsModelingAPI/20230201/OpenAPI.json
- https://www.omg.org/spec/SystemsModelingAPI/20230201/Schemas.json

**Comment by AxelRICHARD** [comment]
Reopen as ElementNavigationServices have not been implemented yet

**Comment by AxelRICHARD** [comment]
The latest official version of the specification can be found here: https://www.omg.org/spec/SystemsModelingAPI/ (https://www.omg.org/spec/SystemsModelingAPI/1.0/Beta2/PDF)
