### ISSUE TITLE
Add the ability to select newly created node

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#3980]
- by default a newly created instance in a tool using the view DSL should be selected
- an API should be available to specify what should be selected instead

**Comment by pcdavid** [comment]
We will leverage the exising `WorkbenchSelection` returned when invoking a tool on a diagram:
```
// diagram.graphqls
type InvokeSingleClickOnTwoDiagramElementsToolSuccessPayload {
  id: ID!
  newSelection: WorkbenchSelection
  messages: [Message]!
}

// core.graphqls
type WorkbenchSelection {
  entries: [WorkbenchSelectionEntry!]!
}

type WorkbenchSelectionEntry {
  id: String!
  label: String!
  kind: String!
}
```

Note that since #3675 the corresponding frontend type `SelectionEntry` no longer includes the `label`.

**Comment by pcdavid** [comment]
AFAICT, the infrastructure to propagate this during the evaluation of model opertations (e.g. `ChildModelOperationHandler`), and to return this as part of the tool's payload (e.g. in `InvokeSingleClickOnDiagramElementToolEventHandler.handle()`) is in place.

However the only place where the `Success.NEW_SELECTION` is actually *set* in the backend seems to be in `NavigationOperationHandler`.

From what I can see, it does not seem to be used on the frontend? It [**was** used](https://github.com/eclipse-sirius/sirius-web/pull/1020/files#diff-3c9a568dac19e8bf6f2c8a1bf8735729b90f435c250bf810207a80bdb59c2571R887) at some point, but it looks like something that has not yet been re-introduced in the new React Flow-based diagrams.
