### ISSUE TITLE
Properties readonly state is too strict on List widget

### ISSUE THREAD

**Issue by wpiers** [eclipse-sirius/sirius-web#4027]
The items in lists are no longer clickable, which reduces the interest of displaying them.
The other widgets become displayed in very light grey, which makes them hard to read.

Making a property readonly should only prevent to edit it.

**Comment by pcdavid** [comment]
The thing is, the "click" and "double-click" behaviors on a list item are specifier-defined, so they *can* actually execute changes (see `mutation clickListItem()` which invoke `ListItem`'s `Function<ClickEventKind, IStatus> clickHandler` which can perform whatever).

**Comment by pcdavid** [comment]
Actually, it makes sense to only avoid the mutation invocations themselves when readOnly, but not the `setSelection` which is also performed in this case, and could make sense even in read-only.
