### ISSUE TITLE
Add Domain DSL 'Domain' name validation

### ISSUE THREAD

**Issue by flatombe** [eclipse-sirius/sirius-web#4222]
* [X ] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

When creating a Domain, the value of attribute 'name' for the Domain is later used to form an EMF URI `domain://name`.

Currently there is no validation for that attribute, meaning specifiers may end up with invalid names, e.g. if a domain is named "My Domain", because the space character is not supported (or should be encoded).

Ideally the validation should ensure that the parsing behavior used to register domains as valid metamodels succeeds.

**Comment by sbegaudeau** [comment]
The validation of domains had not been re-activated in the new architecture, it has been fixed in master
