### ISSUE TITLE
Make default explorer services reusable at the view level

### ISSUE THREAD

**Issue by gdaniel** [eclipse-sirius/sirius-web#4254]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

The default explorer representation is hardcoded in Sirius Web at the _description_ level.
The explorer now supports multiple tree representations, which are provided as `TreeDescriptions`, potentially defined at the _view_ level.
Services used by the default explorer take `VariableManager` as parameter, which make them practically unusable from trees defined at the _view_ level.

Extracting these services would let custom explorers reuse default explorer behavior easily.
A new API could be created to expose these services:
```java
public interface IExplorerServices {
    boolean hasChildren(Object self, IEditingContext editingContext);
    List<Object> getChildren(Object self, IEditingContext editingContext, List<String> expandedIds, List<String> activeFilterIds);
   // Other services used by the explorer
}
```

Existing default explorer services would rely on this API to compute their actual result.

### Cuttings backs

Nothing identified.

### Potential side effects

The `IExplorerTreeItemAlteredContentProvider` interface (which applies filters on the explorer) requires a `VariableManager` as parameter.
Since this interface may be implemented by downstream applications, its signature won't be updated and the associated filtering behavior will stay in the existing services.
This implies that custom explorer implementations will have to handle filters explicitly.

### Describe alternatives you've considered

Migrating the default explorer as a _view_ (instead of a _description_) would be another way to tackle the issue, but it is more complicated. The proposed solution is a first step in this direction.

**Comment by sbegaudeau** [comment]
> Migrating the default explorer as a view (instead of a description) would be another way to tackle the issue, but it is more complicated

It's not just more complicated, it would be at least a net regression in terms of performance for not much gain.

You also have to keep in mind that we need to make OUR explorer evolve over time so the behavior and signature of those methods will change potentially significantly. Are you sure that you want to "copy our behavior" and not have your own behavior (even if it starts with a copy of our own)?

I just want to be sure that you want to mimic OUR explorer on the long run because if you go this way, we WILL one day change how we do things, you WILL be impacted and we may not change back our new behavior.

**Comment by gdaniel** [comment]
Here is my rationale:
1. I want to create a new custom explorer that extends the existing one with, let's say, a new directory containing things I'll manage.
2. To get started, I'd like to first replicate the existing explorer. This is not trivial to do right now **if I have defined my tree at the view level** (I don't have any built-in services to call to perform the same actions as in the explorer)
3. I create my custom explorer services, reusing the default ones when needed
4. If a default service doesn't work as expected for me, I create my own

I understand your point about the future evolutions of the explorer. In this context, it makes sense to start with a copy of Sirius Web's behavior, but it would be easier to copy the `ExplorerServices` file I propose, instead of copying and adapting the description-level functions that are already implemented to make them work with my view-level tree.

All this reasoning is based on the fact that I'd like to define my custom explorer at the view level, but it is maybe not the way to go about it (especially given your point on performances).

**Comment by sbegaudeau** [comment]
I understand why it would be helpful for you. If that's ok for you I don't mind having this service class, I just want you to be aware that there will be changes in its behavior and API.
