### ISSUE TITLE
Ask for confirmation before all destructive operations

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#462]
### Problem

Some operations like deleting a representation or an element (and all its descendants) from the explorer are destructive, but currently they do not ask for confirmation before.
Deleting a whole document _does_ ask for confirmation, but there is no particular reason to treat documents differently from e.g. the root elements inside of them (deleting _them_ is as impacting as deleting the document).

### Solution

Make the confirmation dialog available on all concepts of the explorer (objects, representations, etc)

### No-gos

* A large set of validation rules for specific DSLs
* Dynamic contributions of additional validation rules.

### Test

* [ ] Automated developer tests merged and pass (with reasonable code coverage)
* [ ] Automated End-to-End tests  merged and pass (Cypress)
* [ ] Feature/bug fix manually tested/validated by at least one person not involved in the implementation
* [ ] Collaborative tests passed by hand
* [ ] Exploratory test passed by MEB
* [ ] Business acceptance test passed by MEB

### Doc
* [ ] Internal Doc updated
* [ ] External Doc updated
* [ ] Validation Doc updated

### UX/UI
* [ ] Zeroheight updated
* [ ] Storybook updated

### Next
* [ ] Any left-over tasks added to the issues on Github

**Comment by sbegaudeau** [comment]
I'm removing it from the 0.4.0 milestone since it may arrived in this milestone but it's not sure for the moment.

**Comment by pcdavid** [comment]
See https://github.com/eclipse-sirius/sirius-web/issues/3089 which covers this.
