### ISSUE TITLE
Documentation website(ocpmodeler.com) is down!

### ISSUE THREAD

**Issue by mt-empty** [eclipse-sirius/sirius-web#50]
I noticed the [documentation website](https://ocpmodeler.com/doc/2020.10.0/help_center.html#_sirius_desktop_compatibility) is still down. I hope its not because of the recent fire at OVHcloud's data centre.

Here is the cached version https://webcache.googleusercontent.com/search?q=cache:https://ocpmodeler.com/doc/2020.10.0/help_center.html#_sirius_desktop_compatibility

And this is the `Developer Guide` section in case the cached version gets deleted.

-----------------------
## Developer Guide

This sections describes the main APIs that are exposed by the Obeo Cloud Platform Modeler to build custom modelers and extend the platform.

Every instance of the Obeo Cloud Platform Modeler is a custom Spring Boot application built by using reusable frontend and backend components provided by the Open Source Sirius Components project. When running on the entreprise version of the Obeo Cloud Platform Modeler, additional, proprietary components are available to provide more features, but the principles are the same.

The Sirius Web repository provides an example of a complete, ready-to-run studio based on the Open Source components. It can be used as a starting point to create your own modeler.
### 4. Business Domain Definition

While the architecture of the Obeo Cloud Platform Modeler is not tied to the Eclipse Modeling Framework, EMF models are currently the first supported type of domain models.

If you have an existing EMF metamodel which represents your business domain, to use it in you modeler you need to:

1. Make sure the JARs for the metamodel itself and its .edit support are in your application’s classpath. Typically this involves publishing the two JARs in a Maven repository and adding their coordinates into your sample application’s POM file. Example in Sirius Web.

2. Register your metamodel in your application. This is done by creating a Spring @Configuration which provides your meta-model’s EPackage and AdapterFactory as Spring @Beans. Example in Sirius Web.

3. Provide an implementation of org.eclipse.sirius.web.api.services.IImagePathService which tells Obeo Cloud Platform Modeler in which folders (relative to the root of the JAR) the icons for your metamodel types can be found. Example in Sirius Web.

If you do not yet have an EMF-based domain model, you can use Ecore Tools to design and implement it, and then follow the same steps as above.
### 5. Sirius Desktop Compatibility

Modelers based on the Obeo Cloud Platform Modeler can reuse Sirius Desktop modeler definition files (.odesign files). Only a subset of the Sirius Desktop features are currently supported, but you can safely use a complete odesign file in the Obeo Cloud Platform Modeler. The features which are not supported at the moment will simply be ignored. Future versions of the Obeo Cloud Platform Modeler will increase the scope of Sirius Desktop features supported. If you rely on specific features from Sirius Desktop, do not hesitate to contact us.

The Obeo Cloud Platform Modeler currently only supports a subset of Sirius diagrams and properties views. Tables, trees, and sequence diagrams are not supported at the moment.

For diagrams, the Obeo Cloud Platform Modeler currently supports the main features of:

* nodes and containers;

* relation-based and element-based edges;

* border nodes;

* style customizations;

* creation tools, direct-edit tools, generic tools.

For properties view, the following widgets are supported:

* text fields and text areas;

* checkboxes;

* radio buttons;

* select/combos;

* lists (read-only).

To use an existing odesign modeler definition in the Obeo Cloud Platform Modeler:

1. Make sure the JAR which contains the modeler definition is in your application’s classpath. Typically this involves publishing the .design JAR in a Maven repository and adding its coordinates into your sample application’s POM file. Example in Sirius Web.

2. In your application, provide a Spring @Configuration which implements org.eclipse.sirius.web.compat.services.api.ISiriusConfiguration and tells the platform the path (inside the JAR) where the .odesign file is available. Example in Sirius Web

**Comment by mbats** [comment]
Yes this is due to the OVH fire, we are working on making it up again. Sorry for the delay. I will post here when it will be available again.

**Comment by mbats** [comment]
It is back to normal, the documentation is available : https://ocpmodeler.com/doc/welcome_help_center.html
