### ISSUE TITLE
How to work with multiple user

### ISSUE THREAD

**Issue by burhanayan** [eclipse-sirius/sirius-web#51]
Hi!

At "Sirius Web" Website I see "Shared Projects". How is possible to work with multiple user while sirius-web runs only with "system" user. Is there an easy way to implement this multiuser functionality?

Thanks.

**Comment by mbats** [comment]
Sirius Web supports concurrent edition from multiple clients (web browsers), but they are all treated as the same user by the backend. Handling multiple separate users with fine grained access management is part of OCP commercial offering which is based on Sirius Web : https://www.obeosoft.com/en/products/obeo-cloud-platform

**Comment by sbegaudeau** [comment]
I'll close this issue since an answer has been provided, if you have another question feel free to reopen it or create a new issue.
