### ISSUE TITLE
Manipulating model-instances after creation

### ISSUE THREAD

**Issue by scorch95** [eclipse-sirius/sirius-web#53]
Hi, first I would like to thank you for this amazing project. I think this has so much potential.

I really experimented a lot with this the past days and I am curious if there is the possibility to change the Model-Instances (EObjects) programatically. I've already seen that new EObjects are created in StereotypeDescriptionRegistryConfigurer and I can manipulate them there, which has the desired effect. But then they get wrapped in a JSON Resource and dissappear in the depths of sirius-components ;-)
Is there a way to retrieve them again that I am not aware of? Where should I start if i would try to implement such an api?

Thank you and have a great week.

**Comment by pcdavid** [comment]
Hi, thanks for your interest!

The behavior of a concrete Sirius-based modele (be it Sirius Desktop or Sirius Web) is defined by a _representation description_ which is interpreted at runtime. These contain (among other things) _tool definitions_ which define what modification(s) to perform on the model when the end-user triggers the tool. Most tools have a very simple beahvior (e.g. change the value of an attribute, create a new `EObject`, etc.) but they can actually perform (almost) arbritrary manipulations on the model.

If your modeler is defined using a Sirius Desktop `odesign` file, please refer to [the documentation](https://www.eclipse.org/sirius/doc/specifier/Sirius%20Specifier%20Manual.html) on how to define the behavior of your tools (but note that Sirius Web does not currently support all features of Sirius Desktop modeler definitions.

If your modeler is defined directly using the Sirius Web APIs (i.e. you provide a `org.eclipse.sirius.web.diagrams.description.DiagramDescription` instance that you built programmatically), at some point you need to provide a `org.eclipse.sirius.web.diagrams.tools.CreateNodeTool` which has a handler of type `Function<VariableManager, Status>`. The Java function you provide here will get (through the `VariableManager`) information about the element (`EObject`) on which the user invoked your tool, and from there you can use classical Java/EMF APIs to perform the model manipulations you want.

Note that for diagrams we currently only support _CreateNodeTool_ and _CreateEdgeTool_, but the core does not really care what they do, and a _CreateNodeTool_ can actually do something else than creating a new node.

**Comment by scorch95** [comment]
Thanks for your reply. 
Right now I am using an .odesign file to define my representation. The problem i have with tools is that they are always triggered by end-user as you have written. I want them to be triggered from an external event or something similar. 
To give an example with the flow model: I do not want to insert the temperature of the system manually but from an external source (e.g. the "real" System). 
I will have a closer look at the sirius web api to see if I can use it for that. Anyways thanks for your reply again, that already helped a lot!

**Comment by pcdavid** [comment]
I see.

Then the approach would be to extend our GraphQL API with custom mutations that correspond to the external events, and then invoke these mutations from the external system.
That's how the frontend asks the backend to perform operations, and the mechanism is extensible.

Have a look at the existing mutations like for example `org.eclipse.sirius.web.graphql.datafetchers.mutation.MutationCreateChildDataFetcher`. Adding a new one can be a little cumbersome but not complicated (at least if you are already familiar with GraphQL).

Basically you need:
* an input type which represents the parameters of the mutation (e.g. `org.eclipse.sirius.web.services.api.objects.CreateChildInput`)
* a data fetcher that GraphQL will invoke (with the input as argument) when it receives the mutation request (e.g. `org.eclipse.sirius.web.graphql.datafetchers.mutation.MutationCreateChildDataFetcher`
* make sure the mutation and new types you add are correctly registered in the GraphQL Schema
* in your data fetcher implementation, follow the pattern used by `MutationCreateChildDataFetcher` for example to dispatch the request to the `editingContextEventProcessorRegistry`, which itself will dispatch it to the `IEditingContextEventProcessor` that handles the target project (each project has a single event processor to manage it)
* create an actual event handler following the model of `org.eclipse.sirius.web.spring.collaborative.handlers.CreateChildEventHandler`; it will get invoked in the proper context where you can have access to the actual model instances.

**Comment by scorch95** [comment]
Thank you. I tried it and it seems like this is going to solve my problem (when I am a bit further into GraphQL. ;-) ).

**Comment by scorch95** [comment]
I'm sorry to bother you again but im really close to get things working.

In my EventHandler I try to retrieve the parent Object-instance I automatically want to create a Child for (basically the same way as it is done in `org.eclipse.sirius.web.spring.collaborative.handlers.CreateChildEventHandler`). 
For this I used `IObjectService.getObjects(IEditingContext editingContext, String objectId)`. I had a closer look at this but I'am not sure where I find the `objectId`-String nor what this String actually should contain.

Apart from that everything in seems to work fine. I'm just missing this String to get it into my domain model.
