### ISSUE TITLE
Application run error

### ISSUE THREAD

**Issue by dmitry-kosarevsky99** [eclipse-sirius/sirius-web#6]
Hello!

When I try to run application jar file, error 'Could not resolve placeholder 'sirius.web.graphql.websocket.allowed.origins' in value "${sirius.web.graphql.websocket.allowed.origins}' occurs. I've tried both on docker and local PostgreSQL server on Windows 10.
What has gone wrong? I would appreciate any solutions. A complete error log can be found in attached text file.
[Sirius web run error log.txt](https://github.com/eclipse-sirius/sirius-web/files/5582074/Sirius.web.run.error.log.txt)

**Comment by kobzarvs** [comment]
+1

**Comment by kobzarvs** [comment]
> Hello!
> 
> When I try to run application jar file, error 'Could not resolve placeholder 'sirius.web.graphql.websocket.allowed.origins' in value "${sirius.web.graphql.websocket.allowed.origins}' occurs. I've tried both on docker and local PostgreSQL server on Windows 10.
> What has gone wrong? I would appreciate any solutions. A complete error log can be found in attached text file.
> [Sirius web run error log.txt](https://github.com/eclipse-sirius/sirius-web/files/5582074/Sirius.web.run.error.log.txt)

`java -jar -Dspring.profiles.active=dev sirius-web-sample-application-0.0.1-SNAPSHOT.jar \
          --spring.datasource.url=jdbc:postgresql://localhost:5433/sirius-web-db \
          --spring.datasource.username=dbuser \
          --spring.datasource.password=dbpwd \
          --spring.liquibase.change-log=classpath:db/changelog/sirius-web.db.changelog.xml`

**Comment by dmitry-kosarevsky99** [comment]
Thank you, it solved this and I can run it, blank page appears though :D 👍

**Comment by kobzarvs** [comment]
> Thank you, it solved this and I can run it, blank page appears though :D

can you show the output to terminal and browser console? what browser are you using?

**Comment by pcdavid** [comment]
Thanks @kobzarvs for providing the answer. We will update the documentation.

**Comment by dmitry-kosarevsky99** [comment]
> 
> can you show the output to terminal and browser console? what browser are you using?

So far I've run application in Opera (v 72.0.3815.320) and Microsoft Edge(Version 87.0.664.47). 
Output from terminal and browser console can be found in the attached files.
[Sirius web run terminal logs.txt](https://github.com/eclipse-sirius/sirius-web/files/5588477/Sirius.web.run.terminal.logs.txt)
[Sirius web browser console output.log](https://github.com/eclipse-sirius/sirius-web/files/5588478/Sirius.web.browser.console.output.log)

**Comment by pcdavid** [comment]
We currently only support Chrome-based browsers. Firefox mostly works, but there are some issues on the diagram part with it.
We intend to support more later, but for now while we are in beta we focus on Chrome.

**Comment by pcdavid** [comment]
Actually your error looks similar to https://github.com/ReactTraining/react-router/issues/7032, so it might be an issue on our side in how we manage our dependencies, and not something browser-related.

Which version of node/npm are you using?

What does `npm ls path-to-regexp` give you?

**Comment by dmitry-kosarevsky99** [comment]
> Actually your error looks similar to [ReactTraining/react-router#7032](https://github.com/ReactTraining/react-router/issues/7032), so it might be an issue on our side in how we manage our dependencies, and not something browser-related.
> 
> Which version of node/npm are you using?
> 
> What does `npm ls path-to-regexp` give you?

Npm version is 6. 14.8. Node version is 14.15.0
Given command gives this:  `-- (empty)

**Comment by pcdavid** [comment]
I guess this seems to confirm the bug is similar to the one reported on react-router, but this means the root cause is in the way we manage our dependencies (in particular peer dependencies).

I don't understand why the same sources, with the same versions of Node/NPM produce different results for you than for us though.

If you explictly `npm install path-to-regexp`, does it fix the issue? Or are there others like it lurking behind?

**Comment by dmitry-kosarevsky99** [comment]
> I guess this seems to confirm the bug is similar to the one reported on react-router, but this means the root cause is in the way we manage our dependencies (in particular peer dependencies).
> 
> I don't understand why the same sources, with the same versions of Node/NPM produce different results for you than for us though.
> 
> If you explictly `npm install path-to-regexp`, does it fix the issue? Or are there others like it lurking behind?

So I have run given command in frontend directory, then went through build steps again and it runs just fine now!
Thank you all who helped me with my issue. Since problem is solved, I am closing this issue.
