### ISSUE TITLE
How to deploy sirius-web into Tomcat?

### ISSUE THREAD

**Issue by burhanayan** [eclipse-sirius/sirius-web#67]
Hi!

I would like to deploy sirius-web into Apache Tomcat. Is there a guidance that I can follow? Could you help me about it?

Thanks.

**Comment by pcdavid** [comment]
Hi.

Sirius Web already uses Tomcat as its servlet enging, but indirectly via Spring Boot which does the heavy lifting for us.

I'm not familiar enough with Tomcat to help you directly, but it seems there are ways to deploy a Spring Boot app into Tomcat, see for example https://www.baeldung.com/spring-boot-war-tomcat-deploy
We use Spring Boot in a very "classical" way, so any general documentation on how to deploy Spring Boot apps into Tomcat should apply.
